export const MAKES = [
    'Audi', 'BMW', 'Citroen', 'Fiat', 'Ford', 'Honda', 'Hyundai', 'Jeep', 'Kia',
    'Lexus', 'Mazda', 'Mercedes-Benz', 'Mini', 'Mitsubishi', 'Nissan', 'Opel',
    'Peugeot', 'Porsche', 'Renault', 'Seat', 'Skoda', 'Subaru', 'Suzuki', 'Toyota',
    'Volkswagen', 'Volvo', 'Inne',
] as const;

export const MODELS_BY_MAKE: Record<string, string[]> = {
    Audi: ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'TT', 'R8', 'e-tron'],
    BMW: ['Seria 1', 'Seria 2', 'Seria 3', 'Seria 4', 'Seria 5', 'Seria 6', 'Seria 7', 'Seria 8',
        'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i3', 'i4', 'iX'],
    Citroen: ['C1', 'C3', 'C4', 'C5', 'C5 Aircross', 'Berlingo', 'Cactus', 'DS3', 'DS4'],
    Fiat: ['500', '500X', 'Panda', 'Punto', 'Tipo', 'Doblo', 'Bravo'],
    Ford: ['Fiesta', 'Focus', 'Mondeo', 'Kuga', 'Puma', 'EcoSport', 'Edge', 'Galaxy', 'S-Max', 'Ka', 'Mustang', 'Transit'],
    Honda: ['Civic', 'Accord', 'CR-V', 'HR-V', 'Jazz', 'e'],
    Hyundai: ['i10', 'i20', 'i30', 'i40', 'Tucson', 'Santa Fe', 'Kona', 'Ioniq', 'Elantra'],
    Jeep: ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler'],
    Kia: ['Picanto', 'Rio', 'Ceed', 'Sportage', 'Sorento', 'Niro', 'Stonic', 'XCeed', 'EV6'],
    Lexus: ['CT', 'IS', 'ES', 'GS', 'RX', 'NX', 'UX', 'LS'],
    Mazda: ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-30', 'MX-5'],
    'Mercedes-Benz': ['Klasa A', 'Klasa B', 'Klasa C', 'Klasa E', 'Klasa S', 'CLA', 'CLS',
        'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Vito', 'Sprinter'],
    Mini: ['Cooper', 'Clubman', 'Countryman', 'One'],
    Mitsubishi: ['Space Star', 'ASX', 'Outlander', 'Eclipse Cross', 'L200'],
    Nissan: ['Micra', 'Note', 'Juke', 'Qashqai', 'X-Trail', 'Leaf', 'Navara'],
    Opel: ['Corsa', 'Astra', 'Insignia', 'Mokka', 'Crossland', 'Grandland', 'Zafira', 'Vivaro'],
    Peugeot: ['108', '208', '308', '508', '2008', '3008', '5008', 'Partner'],
    Porsche: ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', 'Boxster', 'Cayman'],
    Renault: ['Clio', 'Megane', 'Talisman', 'Captur', 'Kadjar', 'Koleos', 'Scenic', 'Twingo', 'Laguna'],
    Seat: ['Ibiza', 'Leon', 'Ateca', 'Arona', 'Tarraco', 'Alhambra'],
    Skoda: ['Fabia', 'Octavia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq', 'Scala', 'Rapid'],
    Subaru: ['Impreza', 'Forester', 'Outback', 'XV', 'Legacy'],
    Suzuki: ['Swift', 'Vitara', 'S-Cross', 'Ignis', 'Jimny'],
    Toyota: ['Yaris', 'Corolla', 'Camry', 'RAV4', 'C-HR', 'Auris', 'Avensis', 'Land Cruiser', 'Prius', 'Aygo'],
    Volkswagen: ['Polo', 'Golf', 'Passat', 'Tiguan', 'Touareg', 'T-Roc', 'T-Cross', 'Arteon', 'Up!', 'Sharan', 'Caddy'],
    Volvo: ['S60', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
};
