export interface EquipmentCategory {
    key: string;
    label: string;
    options: { code: string; label: string }[];
}

export const EQUIPMENT_CATEGORIES: EquipmentCategory[] = [
    {
        key: 'audio',
        label: 'Audio i multimedia',
        options: [
            {code: 'apple_carplay', label: 'Apple CarPlay'},
            {code: 'android_auto', label: 'Android Auto'},
            {code: 'bluetooth', label: 'Interfejs Bluetooth'},
            {code: 'radio', label: 'Radio'},
            {code: 'hands_free', label: 'Zestaw głośnomówiący'},
            {code: 'usb', label: 'Gniazdo USB'},
            {code: 'wireless_charging', label: 'Ładowanie bezprzewodowe urządzeń'},
            {code: 'navigation', label: 'System nawigacji satelitarnej'},
            {code: 'sound_system', label: 'System nagłośnienia'},
            {code: 'head_up_display', label: 'Wyświetlacz typu Head-Up'},
            {code: 'touchscreen', label: 'Ekran dotykowy'},
            {code: 'voice_control', label: 'Sterowanie funkcjami pojazdu za pomocą głosu'},
            {code: 'internet_access', label: 'Dostęp do internetu'},
        ],
    },
    {
        key: 'comfort',
        label: 'Komfort',
        options: [
            {code: 'climate_control', label: 'Klimatyzacja automatyczna'},
            {code: 'rear_climate_control', label: 'Klimatyzacja dla pasażerów z tyłu'},
            {code: 'sunroof', label: 'Dach otwierany / przesuwny'},
            {code: 'sun_visor', label: 'Osłona przeciwsłoneczna'},
            {code: 'leather_upholstery', label: 'Tapicerka skórzana'},
            {code: 'electric_seats_driver', label: 'Elektrycznie ustawiany fotel kierowcy'},
            {code: 'electric_seats_passenger', label: 'Elektrycznie ustawiany fotel pasażera'},
            {code: 'heated_seats_front', label: 'Podgrzewane fotele przednie'},
            {code: 'heated_seats_rear', label: 'Podgrzewane fotele tylne'},
            {code: 'ventilated_seats', label: 'Wentylowane fotele przednie'},
            {code: 'massage_seats', label: 'Fotele z funkcją masażu'},
            {code: 'memory_seats', label: 'Siedzenie z pamięcią ustawienia'},
            {code: 'sport_seats', label: 'Sportowe fotele'},
            {code: 'armrest', label: 'Podłokietnik'},
            {code: 'leather_steering_wheel', label: 'Kierownica skórzana'},
            {code: 'heated_steering_wheel', label: 'Podgrzewana kierownica'},
            {code: 'keyless_entry', label: 'Keyless Entry / Keyless Go'},
            {code: 'keyless_start', label: 'Uruchamianie silnika bez użycia kluczyków'},
            {code: 'parking_heater', label: 'Ogrzewanie postojowe'},
            {code: 'rain_sensor', label: 'Czujnik deszczu'},
            {code: 'heated_windshield', label: 'Podgrzewana przednia szyba'},
            {code: 'electric_windows', label: 'Elektryczne szyby'},
            {code: 'tinted_windows', label: 'Przyciemniane szyby'},
            {code: 'electric_sunroof', label: 'Elektrycznie otwierany dach'},
            {code: 'tow_hook', label: 'Hak holowniczy'},
        ],
    },
    {
        key: 'driver_assist',
        label: 'Systemy wspomagania kierowcy',
        options: [
            {code: 'cruise_control', label: 'Tempomat'},
            {code: 'adaptive_cruise_control', label: 'Tempomat adaptacyjny'},
            {code: 'front_parking_sensors', label: 'Czujniki parkowania przednie'},
            {code: 'rear_parking_sensors', label: 'Czujniki parkowania tylne'},
            {code: 'park_assist', label: 'Asystent parkowania'},
            {code: 'camera_360', label: 'Kamera cofania / panoramiczna 360°'},
            {code: 'electric_mirrors', label: 'Lusterka boczne ustawiane elektrycznie'},
            {code: 'heated_mirrors', label: 'Podgrzewane lusterka boczne'},
            {code: 'folding_mirrors', label: 'Lusterka boczne składane elektrycznie'},
            {code: 'blind_spot_assist', label: 'Asystent martwego pola'},
            {code: 'lane_assist', label: 'Asystent utrzymania pasa ruchu'},
            {code: 'distance_control', label: 'Kontrola odległości od poprzedzającego pojazdu'},
            {code: 'speed_limiter', label: 'Ogranicznik prędkości'},
            {code: 'traffic_sign_recognition', label: 'System rozpoznawania znaków drogowych'},
            {code: 'hill_holder', label: 'Wspomaganie ruszania pod górę (Hill Holder)'},
            {code: 'traction_control', label: 'Kontrola trakcji'},
            {code: 'collision_warning', label: 'System ostrzegający o możliwej kolizji'},
            {code: 'emergency_braking', label: 'Asystent hamowania awaryjnego'},
            {code: 'driver_fatigue_monitor', label: 'System wykrywania zmęczenia kierowcy'},
            {code: 'adaptive_headlights', label: 'Oświetlenie adaptacyjne'},
            {code: 'led_headlights', label: 'Reflektory LED'},
            {code: 'xenon_headlights', label: 'Reflektory ksenonowe'},
            {code: 'fog_lights', label: 'Lampy przeciwmgielne'},
            {code: 'daytime_running_lights', label: 'Światła do jazdy dziennej'},
            {code: 'start_stop', label: 'System Start/Stop'},
            {code: 'tire_pressure_monitor', label: 'Elektroniczna kontrola ciśnienia w oponach'},
        ],
    },
    {
        key: 'safety',
        label: 'Bezpieczeństwo',
        options: [
            {code: 'abs', label: 'ABS'},
            {code: 'esp', label: 'ESP'},
            {code: 'driver_airbag', label: 'Poduszka powietrzna kierowcy'},
            {code: 'passenger_airbag', label: 'Poduszka powietrzna pasażera'},
            {code: 'side_airbags', label: 'Boczne poduszki powietrzne'},
            {code: 'curtain_airbags', label: 'Kurtyny powietrzne'},
            {code: 'knee_airbags', label: 'Poduszka powietrzna kolan'},
            {code: 'isofix', label: 'Isofix (punkty mocowania fotelika dziecięcego)'},
            {code: 'alarm', label: 'Alarm'},
            {code: 'immobilizer', label: 'Immobilizer'},
            {code: 'central_locking', label: 'Centralny zamek'},
        ],
    },
    {
        key: 'performance',
        label: 'Osiągi i tuning',
        options: [
            {code: 'alloy_wheels', label: 'Felgi aluminiowe'},
            {code: 'sport_suspension', label: 'Zawieszenie sportowe'},
            {code: 'adjustable_suspension', label: 'Zawieszenie regulowane'},
            {code: 'pneumatic_suspension', label: 'Zawieszenie pneumatyczne'},
            {code: 'ceramic_brakes', label: 'Hamulce z kompozytów ceramicznych'},
            {code: 'particulate_filter', label: 'Filtr cząstek stałych'},
        ],
    },
    {
        key: 'electric',
        label: 'Samochody elektryczne',
        options: [
            {code: 'regen_braking', label: 'System odzyskiwania energii'},
            {code: 'fast_charging', label: 'Funkcja szybkiego ładowania'},
            {code: 'charging_cable', label: 'Kabel do ładowania'},
        ],
    },
];

export const EQUIPMENT_LABELS: Record<string, string> = Object.fromEntries(
    EQUIPMENT_CATEGORIES.flatMap(cat => cat.options.map(o => [o.code, o.label]))
);
