// Generated from the otomoto.pl search filters ("Marka pojazdu" / "Model pojazdu") of each category.
// Like on otomoto, only passenger cars and motorcycles have a model list; other categories use a free-text model.
import type {VehicleCategory} from '../types';

export const MAKES_BY_CATEGORY: Record<VehicleCategory, readonly string[]> = {
    PASSENGER: [
        'Abarth', 'Acura', 'Aito', 'Aiways', 'Aixam', 'Alfa Romeo', 'Alpine', 'Arcfox', 'Ariel', 'Artega',
        'Asia', 'Aston Martin', 'Audi', 'Austin', 'Autobianchi', 'AVATR', 'BAIC', 'Bajaj', 'BAW', 'Bentley',
        'Bentu', 'Bestune', 'Biro', 'Blaval', 'BMW', 'BMW-ALPINA', 'Brilliance', 'Bugatti', 'Buick', 'BYD',
        'Cadillac', 'Casalini', 'Caterham', 'Cenntro', 'Changan', 'Chatenet', 'Chery', 'Chery Fulwin',
        'Chevrolet', 'Chrysler', 'Citroen', 'Cupra', 'Dacia', 'Daewoo', 'Daihatsu', 'DEEPAL', 'DeLorean',
        'Denza', 'DFM', 'DFSK', 'DKW', 'Dodge', 'Dongfeng', 'Doosan', 'DR MOTOR', 'DS Automobiles', 'e.GO',
        'Eagle', 'Elaris', 'Eletroride', 'Exlantix', 'FAW', 'FENDT', 'Ferrari', 'Fiat', 'Fisker', 'Ford',
        'Forthing', 'FOTON', 'GAC', 'Gaz', 'Geely', 'Genesis', 'GMC', 'GWM', 'HiPhi', 'Honda', 'Hongqi',
        'Hummer', 'Hyundai', 'iamelectric', 'ICH-X', 'Ineos', 'Infiniti', 'Isuzu', 'Iveco', 'JAC', 'Jaecoo',
        'Jaguar', 'Jeep', 'Jetour', 'Jinpeng', 'Kia', 'KTM', 'Lada', 'Lamborghini', 'Lancia', 'Land Rover',
        'Leapmotor', 'LEVC', 'Lexus', 'Li', 'Ligier', 'Lincoln', 'Lixiang', 'Lotus', 'LTI', 'Lucid',
        'Lynk & Co', 'Maextro', 'MAN', 'Maserati', 'MAXIMUS', 'Maxus', 'Maybach', 'Mazda', 'McLaren',
        'Melex', 'Mercedes-Benz', 'Mercury', 'MG', 'Microcar', 'Mini', 'Mitsubishi', 'Morgan', 'NIO',
        'Nissan', 'Nysa', 'Oldsmobile', 'Omoda', 'Opel', 'Peugeot', 'Piaggio', 'Plymouth', 'Polestar',
        'Polonez', 'Pontiac', 'Porsche', 'RAM', 'Renault', 'Rivian', 'Rolls-Royce', 'Rover', 'Rox', 'Saab',
        'SARINI', 'Saturn', 'Seat', 'Seres', 'Shuanghuan', 'Simca', 'Skoda', 'Skywell', 'Skyworth', 'Smart',
        'Sportequipe', 'SsangYong/KGM', 'Stelato', 'Subaru', 'Suzuki', 'Swapa', 'SWM', 'Syrena', 'Tarpan',
        'Tata', 'Tazzari', 'Tesla', 'Toyota', 'Trabant', 'Triumph', 'TUATARA', 'Uaz', 'Vanderhall',
        'Vauxhall', 'VELEX', 'Volkswagen', 'Volvo', 'Voyah', 'Warszawa', 'Wartburg', 'Wey', 'Wołga',
        'Xiaomi', 'XPeng', 'Zaporożec', 'Zastava', 'ZEEKR', 'Zefir', 'Zhidou', 'Żuk', 'Inne',
    ],
    TRUCK: [
        'ACTM', 'Aebi', 'Akpil', 'ATC', 'Autosan', 'Avia', 'Bedford', 'Berliet', 'BMC', 'Boschung', 'Bova',
        'BYD', 'Chevrolet', 'Citroën', 'Dacia', 'DAF', 'Dennis', 'FENDT', 'Fiat', 'Ford', 'Forester',
        'FOTON', 'France Elevateur', 'Freightliner', 'FUSO', 'Gaz', 'Ginaf', 'GMC', 'Grove', 'Ifa',
        'International', 'Irisbus', 'Irizar', 'Isuzu', 'Iveco', 'JAC', 'Jelcz', 'Johnston', 'Kadussis',
        'Kamaz', 'Karsan', 'Kenworth', 'Kia', 'Kogel', 'Krone', 'Lamberet', 'Liaz', 'Liebherr', 'Mafi',
        'Magirus', 'MAN', 'Maz', 'Mazda', 'Meiller', 'Mercedes-Benz', 'Mitsubishi', 'Moderntech', 'Mol',
        'Movex', 'Multicar', 'Neoplan', 'Nissan', 'Opel', 'Otokar', 'Peugeot', 'Remet CNC Technology',
        'Renault', 'Robur', 'SaMASZ', 'Scania', 'Schmidt', 'Schmitz', 'Setra', 'Solaris', 'Sommer', 'Star',
        'Steyr', 'Tata', 'Tatra', 'Temsa', 'Terberg', 'Toyota', 'Uaz', 'Unimog', 'Van Hool', 'VDL',
        'Versalift', 'Volkswagen', 'Volvo', 'WALTRA', 'WEB Trailer', 'Wielton', 'WUMAG', 'Ził', 'Škoda',
        'Inne',
    ],
    CONSTRUCTION: [
        'ABG', 'Aebi', 'Aebi Schmidt', 'Ahlmann', 'Allrad', 'AMLIFT', 'Ammann', 'APS', 'Arcomet', 'Atlas',
        'Atlas Copco', 'Atlet', 'Atmos', 'Ausa', 'Avant', 'AXOLIFT', 'Baka', 'Balkancar', 'Barford',
        'Baukema', 'Baumann', 'Bawoo', 'Befard', 'Belarus', 'Bell', 'Belle', 'Belos', 'Benaty',
        'Berger Kraus', 'Bergmann', 'BIPROMASZ', 'Bison', 'Blizzer', 'BMV', 'Bobcat', 'Bomag', 'BT',
        'Bulmor', 'BV', 'BVT', 'Case', 'CAST', 'Caster', 'Caterpillar', 'Cattaneo', 'Cela', 'Cesab',
        'Chicago Pneumatic', 'Chrast', 'Claas', 'Clark', 'Combilift', 'Compair', 'Crown', 'CT Power', 'CTM',
        'Cummins', 'CUSHMAN', 'Dac', 'Daewoo', 'DAF', 'Dantruck', 'DB Engineering', 'Demag', 'Denyo',
        'Destas', 'Dieci', 'Ditch Witch', 'Doosan', 'Doppstadt', 'Dresser', 'Dressta', 'Dulevo', 'Dynapac',
        'Easy Grader', 'Eder', 'Empro', 'EP', 'Eurocomach', 'Everun', 'Excat', 'Extec', 'Fadroma',
        'Fantuzzi', 'Faresin', 'Fassi', 'Faun', 'Fbgru', 'Fendt', 'Fermec', 'FG Wilson', 'Fiat', 'Finlay',
        'FMGru', 'Ford', 'France Elevateur', 'Fuchs', 'Furukawa', 'Gappa', 'Gehl', 'Genie', 'Genus', 'Giant',
        'Goodsense', 'Grove', 'Günstig', 'Günter Grossmann', 'Hako', 'Hamm', 'Hangcha', 'Hanix', 'Hanomag',
        'Hartl', 'Hartmann', 'Haulotte', 'HBM', 'HC', 'Heden', 'Heli', 'Hen', 'Heracles', 'Hiab', 'Hidromek',
        'Himoinsa', 'Hinowa', 'Hitachi', 'HMF', 'HSW', 'Hubtex', 'Husqvarna', 'Hydrema', 'Hydrotech',
        'Hyster', 'Hyundai', 'Indeco', 'Ingersoll Rand', 'Interbauer', 'Iveco', 'JAMA', 'Jamma', 'Jazgot',
        'JCB', 'Jelcz', 'JLG', 'JMG', 'John Deere', 'Johnston', 'Jumbo', 'Jungheinrich', 'Kaelble',
        'Kaercher', 'Kalmar', 'Kamaz', 'KAMTU', 'KATO', 'Keestrack', 'Keller Kraft', 'Kesla', 'Kingway',
        'Kinshofer', 'KION Baoli', 'KLAAS', 'Kleemann', 'KMM', 'Kobelco', 'Komatsu', 'Konecranes', 'Konig',
        'Kraftwelle', 'Kramer', 'Krupp', 'Kubota', 'LGMG', 'Liaz', 'Libra', 'Liebherr', 'Linde', 'Liu Gong',
        'Locust', 'Lonking', 'LOVOL', 'LSC', 'LuGong', 'Luna', 'MACKS', 'Maeda', 'Magni', 'MAN', 'Manitou',
        'Mantis', 'Masol', 'Massey Ferguson', 'McCloskey', 'Mecalac', 'Mercedes-Benz', 'Merlo', 'MESSERSI',
        'MIKANN', 'Mima', 'Minelli', 'Mini Digger', 'MISATO', 'Mitsubishi', 'MKG', 'Moderntech', 'Moffett',
        'Montabert', 'Mora', 'MOSA', 'Movex', 'Moxy', 'MTZ', 'Multione', 'Neomach', 'New Holland', 'NEX',
        'Nifty', 'Nissan', 'Nobas', 'Noblelift', 'O&K', 'Oil&Steel', 'Okayama', 'Omega', 'Omme', 'Ormet',
        'Ostrówek', 'PALAZZANI', 'Palfinger', 'Paus', 'Peiner', 'Platform Basket', 'Potain', 'Powerscreen',
        'Pramac', 'Promag', 'PROMLIFT', 'PRONAR', 'Putzmeister', 'Raimondi', 'Rammax', 'RCM', 'REDDOT',
        'Remet CNC Technology', 'Renault', 'Rhinoceros', 'Rmf', 'Rocla', 'Roman', 'Rotair', 'Rozzi',
        'Ruthmann', 'Saez', 'SaMASZ', 'Samsung', 'San Marco', 'Sandvik', 'Sany', 'SBM', 'Scania', 'Schaeff',
        'Schäffer', 'SDLG', 'Sennebogen', 'SID', 'Simex', 'Sinoboom', 'Skyjack', 'Snorkel', 'Socage',
        'Sprider', 'Stavostroj', 'Steinbock', 'Steyr', 'Still', 'STIMA', 'Strassmayr', 'Striegel', 'Stroer',
        'SUMITOMO', 'SUNWARD', 'Svetruck', 'Swepac', 'TABE', 'Taian', 'Takeuchi', 'Tatra', 'TCM',
        'Tech-Project', 'Terberg', 'Terex', 'Tesab', 'Thwaites', 'TICAB', 'TOKU', 'TOR-INDUSTRIES',
        'TORQMATIK', 'Toyo', 'Toyota', 'TOZAMET', 'Trevi Benne', 'TUR Poland', 'UniCarriers', 'Unimog',
        'UpRight', 'Valla', 'Venieri', 'Vermeer', 'Versalift', 'Vicario', 'Vogele', 'Volvo', 'Wacker Neuson',
        'Waryński', 'WEBER', 'Weycor', 'WINLET', 'Wirtgen', 'WORKMAX', 'XCMG', 'Yale', 'Yamaguchi', 'Yanmar',
        'Yuchai', 'Zeppelin', 'Zettelmeyer', 'ZMG', 'Zoomlion', 'Inne',
    ],
    VAN: [
        'Abbey', 'Acerbi', 'ACTM', 'ADER', 'Adria', 'AEBI', 'Affinity', 'Ahorn', 'ALKOM', 'Allrad', 'Ammann',
        'Ardor', 'Aro', 'Astra', 'ATC', 'AUSA', 'Autosan', 'Avia', 'Balcamp', 'BANNERT', 'BAVARIA',
        'Bavaria-Camp', 'BAW', 'Bedford', 'Befard', 'Benalu', 'Benimar', 'Berger', 'BERGERecotrail',
        'Berliet', 'Beyerland', 'Blucamp', 'Blyss', 'BMC', 'Bodex', 'Boeckmann', 'Bova', 'Bravia Mobil',
        'Brenderup', 'Burg', 'Burstner', 'BYD', 'Carado', 'Caravelair', 'Carmosino', 'Carnehl', 'Carthago',
        'Case', 'Caterpillar', 'Cenntro', 'Challenger', 'Changhe', 'Chateau', 'Chausson', 'Chereau',
        'Chevrolet', 'Christ', 'Chrysler', 'CI', 'Citroën', 'Claas', 'Clark', 'Cmt', 'Coachman', 'Coldcar',
        'Concorde', 'CS Reisemobile', 'Cummins', 'CUSHMAN', 'Dacia', 'Daewoo', 'DAF', 'Daihatsu', 'Dembell',
        'Depar', 'Dethleffs', 'DFSK', 'Dodge', 'Dreamer', 'Eifelland', 'Elaris', 'Elnagh', 'EMTECH',
        'Etrusco', 'Eura Mobil', 'Eurobody', 'Evum Motors', 'Farizon', 'Faro', 'Feber Inter Cars', 'Fendt',
        'Fermec', 'Fiat', 'Fleetwood', 'Fliegl', 'Ford', 'FOTON', 'Frankia', 'Freightliner', 'Fruehauf',
        'Gaz', 'Giottiline', 'Globe-Traveller', 'GMC', 'Granalu', 'Grappar', 'Gras', 'Gray&Adams', 'Grove',
        'Hendricks', 'Hermanns', 'Hobby', 'Hobur', 'Home-Car', 'Honda', 'Hubiere', 'Hudson', 'Humbaur',
        'Hymer-Eriba', 'Hyster', 'Hyundai', 'Ifa', 'Ikarus', 'Ilusion', 'Irisbus', 'Irizar', 'Isuzu',
        'Itineo', 'Iveco', 'JAC', 'Janmil', 'JCB', 'Jelcz', 'John Deere', 'JONWAY', 'KABE', 'Kaiser',
        'Kamaz', 'Karmann-Mobil', 'Karosa', 'Kel-berg', 'Kenworth', 'Kia', 'King', 'Kip', 'Knapen', 'KNAUS',
        'Kogel', 'Komatsu', 'KOS Camper', 'Kraker Trailers', 'Kramer', 'Kraz', 'Krone', 'Kässbohrer',
        'La Marca', 'LAG', 'Laika', 'Lamberet', 'Langendorf', 'LDV', 'LE VOYAGEUR', 'LEVC', 'Liaz',
        'Liebherr', 'LMC', 'Lohr', 'Lublin', 'Luna', 'Lunar', 'MAC', 'Mack', 'MaDo', 'Magirus', 'Magyar',
        'MAN', 'MASURIA', 'MAX Trailer', 'Maxus', 'Maz', 'Mazda', 'McLOUIS', 'Mega', 'Meiller', 'Melex',
        'MENCI', 'Mercedes-Benz', 'Miller', 'Mistrall', 'Mitsubishi', 'Mobilvetta', 'Montracon', 'Morelo',
        'MTZ', 'Multicar', 'Neoplan', 'Neptun', 'Neuson', 'New Holland', 'Niesmann-Bischoff', 'Niewiadów',
        'Nissan', 'NobelART', 'Nooteboom', 'Nova', 'NPS', 'Nysa', 'O&K', 'OFFICINE BS', 'Opel', 'Orangecamp',
        'Otokar', 'Ovibos', 'P.A.Z.', 'PAXSTER', 'Peterbilt', 'Peugeot', 'Piaggio', 'PILOTE', 'Polonez',
        'Pongratz', 'Possl', 'Praga', 'RAM', 'Randger', 'Rapido', 'Reisch', 'Renault', 'REPO', 'Rimor',
        'Robur', 'Rocar', 'Roller Team', 'Roman', 'Rydwan', 'Samro', 'Scania', 'Schaeff', 'Schmitz',
        'Schwarzmuller', 'Seat', 'Setra', 'Sherp', 'Sidecar', 'Silvergreen', 'Sommer', 'SOR', 'Spitzer',
        'SsangYong', 'Star', 'Stema', 'Sterling', 'Steyr', 'Still', 'Stopexim', 'Subaru',
        'Sun Living by Adria', 'Sunlight', 'Suzuki', 'Swidnik TEMA', 'SYLAND', 'System Trailers', 'Tabbert',
        'Talbot', 'Tarpan', 'Tata', 'Tatra', 'TEC', 'TEMSA', 'Tenax', 'Tisvol', 'Toyota', 'Trailor', 'Uaz',
        'ULTRAND', 'Unimog', 'Ursus', 'Van Hool', 'Vanestro', 'VANNADO', 'VeDeCar', 'Viberti', 'Volkswagen',
        'Volvo', 'Weinsberg', 'Weippert', 'Western Star', 'Westfalia', 'Wielton', 'Wilex', 'Wilk', 'Wiola',
        'XGO Dynamic', 'Yanmar', 'Yutong', 'Zasław', 'Zetor', 'Ził', 'Zorzi', 'Zremb', 'Świdnik', 'Škoda',
        'Żuk', 'Inne',
    ],
    MOTORCYCLE: [
        '79Bike', 'Access', 'Adly', 'Aeon', 'AGM', 'AJP', 'AJS', 'Alfarad', 'Altis Powersports', 'Amperi',
        'APOLLO', 'Aprilia', 'Arctic Cat', 'Ariic', 'ASIX', 'Askoll', 'Bajaj', 'Baotian', 'Barton', 'Bashan',
        'BearEbike', 'Benda', 'Benelli', 'Benyco', 'Benzer', 'Berreta', 'Beta', 'Big Bear Choppers',
        'Big Dog', 'Bili Bike', 'Bili Coco', 'Bimota', 'Blinc', 'BMW', 'BNP', 'Bombardier', 'BOOM',
        'Boss Hoss', 'BPG Werks', 'BRCP', 'Brixton', 'BSA', 'Buell', 'Cagiva', 'CAKE', 'Can-Am', 'CCM',
        'CECTEK', 'CFMoto', 'City-bike', 'Cobra Moto', 'CORVUS', 'COSMOPOLITAN', 'CPI', 'CR&S', 'Cross IMR',
        'CZ', 'Daelim', 'Daytona', 'Derbi', 'Diabolini', 'Dinli', 'DKW', 'Dniepr', 'Doohan', 'Ducati',
        'E Ride Pro', 'E-mio', 'Eagle Motorsports', 'eFun', 'EGL Eglmotor', 'ELECTRORIDE', 'Elon Motors',
        'Energica', 'Enormis', 'Evoyager', 'Fantic', 'Faspider', 'FD MOTORS', 'FECHT', 'Ferro', 'FK Motors',
        'FYM', 'Garelli', 'Gas Gas', 'Gateway', 'GB Motors', 'Geely', 'Generic', 'Gilera', 'Goes',
        'Greenwolke', 'Hanway', 'Harley-Davidson', 'Hartford', 'Hercules', 'Hero', 'HISUN', 'HM', 'Honda',
        'Horwin', 'Hummer', 'Husaberg', 'Husqvarna', 'Hyosung', 'iamelectric', 'IFA', 'Indian', 'Italjet',
        'IŻ', 'Jawa', 'JHL', 'Jincheng', 'JML', 'Journeyman', 'JTG', 'Junak', 'Kandi', 'Kawasaki', 'KAYO',
        'Keeway', 'Kentoya', 'Kespor', 'Kingway', 'Kinroad', 'Komar', 'KOVE', 'KSR Moto', 'KTM', 'KXD',
        'Kymco', 'La Souris', 'Lambretta', 'Laverda', 'Lifan', 'Linhai', 'LIYA', 'LML', 'Loncin', 'Lotus',
        'Lucky Star', 'Macbor', 'Malaguti', 'Masai', 'MBK', 'MIKILON', 'MIR Racing', 'MOMO', 'Mondial',
        'Mondo Motors', 'Morbidelli', 'Moti', 'Moto Guzzi', 'Moto Magnus', 'Moto Morini', 'Motobi',
        'Motomar', 'Motorro', 'Motowell', 'Motron', 'MP Korado', 'MRF', 'MUDRAX', 'Munch', 'MV AGUSTA', 'MZ',
        'Nitro Motors', 'Niu', 'Norton', 'NSU', 'ODES', 'Orange County Choppers (OCC)', 'Pannonia', 'Peda',
        'Pegasus', 'Peugeot', 'Phelon and moore', 'Piaggio', 'Pit Bike IMR', 'Pitgang', 'Polaris',
        'Polovolt', 'Powerland', 'Puch', 'QJMOTOR', 'Quadro', 'RASSLER', 'Redline', 'Rerode', 'Rewaco',
        'REX', 'Rieju', 'RM', 'Romet', 'Royal Enfield', 'Sachs', 'SARINI', 'Scootworks', 'Seat', 'Segway',
        'Sherco', 'SHERP', 'Shineray', 'SHL', 'Simson', 'Skyjet', 'SMC', 'Sokół', 'Stark Future', 'Stels',
        'Summit', 'Sunbeam', 'Super Soco', 'Surron', 'Suzuki', 'SWM', 'SYM', 'Talaria', 'TAO MOTORS', 'TGB',
        'Thumpstar', 'TM', 'Torq', 'Torrot', 'Triango', 'Triton', 'Triumph', 'Tromox', 'TUATARA', 'UM',
        'UPMoto', 'Ural', 'Vectrix', 'VELEX', 'Velocifero', 'Ventus', 'Vespa', 'Victory', 'Vincent', 'Vmoto',
        'VOGE', 'WFM', 'WK', 'WSK', 'X-Moto', 'XMOTOS', 'XTR', 'Yadea', 'Yamaha', 'Yamasaki', 'Yuki', 'YZM',
        'Zast', 'Zefir', 'Zero', 'Zipp', 'Zonda', 'Zongshen', 'Zontes', 'Zumico', 'Zundapp', 'Zuumav',
        'ZX MOTO', 'Inne',
    ],
    TRAILER: [
        'Abi', 'Acerbi', 'Ackermann', 'ACTM', 'ADER', 'Adria', 'Airstream', 'Algema', 'ALKOM', 'ALKORO',
        'Ammann', 'Annaburger', 'Ardor', 'Asko', 'ATC', 'Atcomex', 'ATM', 'Aurepa', 'Aurora', 'AUTO-TECH',
        'Avento', 'Avia', 'Avondale', 'B-XL', 'Bailey', 'BALHANGER', 'BANNERT', 'Bavaria-Camp', 'BC-LDS',
        'BEDNAR', 'Benalu', 'Berdex', 'Berger', 'Besttrailers', 'Beyerland', 'BFG', 'BFZ', 'Blomenröhr',
        'Blomert', 'Blumhardt', 'Blyss', 'BMI', 'Bobinidus', 'Bobrujsk Agromasz', 'Bodex', 'Boeckmann',
        'Boro', 'Bos', 'Brantner', 'Brenderup', 'Brian James Trailers', 'Broshuis', 'BSL', 'Buca',
        'Buccaneer', 'Bulthuis', 'Bunge', 'Bunk', 'Burg', 'Burstner', 'BWW', 'Böckmann', 'C.C.', 'Caldal',
        'Camro', 'Caravelair', 'Carbontear', 'CARELINER', 'Caretta', 'Carmosino', 'Carnehl', 'Carro',
        'Cartwright', 'Castera', 'CC La Mancha', 'Chateau', 'Chereau', 'Cheval Liberte', 'Christ', 'CIMC',
        'Citransa', 'Citroën', 'Cmt', 'Coachman', 'Cobo', 'Coder', 'Cometto', 'Compass', 'Concorde',
        'Contar', 'Cordes-Sottorf', 'Cuppers', 'Cymerman', 'Cynkomet', 'D-TEC', 'DAC', 'DAF', 'Dam',
        'Danson', 'DBM', 'Debon', 'Delta', 'Demarko Special Trailers', 'Dercks', 'Derubis', 'Desot',
        'Dethleffs', 'Digicross', 'Dijkstra', 'Dinkel', 'Doll', 'Draco', 'Drival', 'Ecovrac', 'Eduard',
        'Eggers', 'Eifelland', 'EKERI', 'EkoPOM', 'EKW', 'Elbo', 'Elddis', 'Ellinghaus', 'Elnagh', 'EMTECH',
        'EROGLU', 'ES-GE', 'Esselmann', 'Esterer', 'ESVE', 'Euramobil', 'Farcinox', 'Faro', 'FAUTRAS PROVAN',
        'Faymonville', 'Feber Inter Cars', 'Feldbinder', 'Fendt', 'Fiat', 'Fiault', 'Finkl', 'Fitzel',
        'Flandria', 'Fleetwood', 'Fliegl', 'Floor', 'Ford', 'Foresteel', 'Fracht', 'Frankia', 'Frappa',
        'Frejat', 'Fruehauf', 'FSN', 'FVG', 'Gala BBG', 'Galtrailer', 'Galucho', 'General Trailer',
        'General Trailers', 'Gervasi', 'Geusen', 'GEWE', 'Gheysen en Verpoort', 'Gicalla', 'GIESSE',
        'Gniotpol', 'Gofa', 'Goldhofer', 'Gontrailer', 'Gourdon', 'Graaff', 'Granalu', 'Grapar', 'Gras',
        'Gray&Adams', 'Groenewegen', 'Gromex', 'GRUAU', 'GRW', 'GS', 'GS Meppel', 'Guhur', 'Guillen', 'GVN',
        'Głowacz', 'H&W', 'Hakpol', 'Hammar', 'Hangler', 'Hapert', 'Harcon', 'Heering', 'Heinemann',
        'Hendricks', 'Hermanns', 'Hertoghs', 'HFM', 'HILKEN', 'Hobby', 'Hoenkhaus', 'Hoffmann', 'Homar',
        'Home-Car', 'HONEYtech', 'HRD', 'Huffermann', 'Humbaur', 'Hummel', 'Hydrofast', 'Hymer-Eriba', 'Ifa',
        'Ifor Williams', 'Indox', 'Iveco', 'Janmil', 'Jastech', 'Jelcz', 'Jilko', 'Jotha', 'Jumbo', 'JUNG',
        'Juzjade', 'JW-Tec', 'Kabe', 'Kaiser', 'KamCzepka', 'Karfa', 'KASAN', 'Kassbohrer', 'Keaser',
        'Kel-Berg', 'Kempf', 'Kennis', 'King', 'Kip', 'Klaeser', 'Klaus', 'KMA', 'KMPolska', 'Knapen',
        'Knapen Trailers', 'KNAUS', 'Konar', 'Kotschenreuther', 'Kraker', 'Kraker Trailers', 'Kramer',
        'Kroeger', 'Kroll', 'Kromhout', 'Krone', 'Krukenmeier', 'KTS', 'Kubix', 'Kwb', 'Kögel',
        'Köhler Elmshorn', 'Lag', 'Lahrs', 'Laika', 'Lako', 'Lamberet', 'Lambrecht', 'Langendorf', 'Latre',
        'LeciTrailer', 'Leciñena', 'Legras', 'Leveques', 'Ley', 'Liaz', 'LIDER Trailers', 'Ligthart',
        'Lindenau', 'Lindner', 'Lintrailers', 'LMC', 'Lohr', 'Lorries', 'Louault', 'Lueck', 'Lunar', 'Lück',
        'MAC', 'MACUGA', 'MaDo', 'Magyar', 'Maisonneuve', 'MAN', 'MAR-POL', 'Marshall', 'Marston', 'Martz',
        'MATURI', 'MAX Trailer', 'MAZZO', 'Mefal', 'Mega', 'Meierling', 'Meiller', 'Menci', 'Mercedes Benz',
        'Merker', 'Mersch', 'Metal-Fach', 'Metalchem', 'Metaltech', 'Meusburger', 'MGM Trailers', 'MHS',
        'Michieletto', 'Miller', 'Mirofret', 'Mistrall', 'Mobilvetta', 'Mol', 'Montalban', 'Montenegro',
        'Montracon', 'More Maskiner', 'Mototechnik', 'MTDK', 'Mulder', 'Mustang Strong', 'Möslein',
        'Müller-Mitteltal', 'Nachtman', 'Nadwozia-partner', 'Neptun', 'Netam', 'Netam Fruehauf', 'Nicolas',
        'Niconlift', 'Niewiadów', 'Nooteboom', 'Nova', 'Nowim', 'NPS', 'NT Industry', 'Nursan', 'Närko',
        'Obermaier', 'OBERMANN', 'OFFICINE BS', 'Omar', 'OMT', 'Orten', 'Orthaus', 'OVA', 'Ovibos', 'Pacton',
        'Panav', 'Panissars', 'Parcisa', 'Peischl', 'PERARD', 'Peugeot', 'Pezzaioli', 'Piaggio', 'Plandex',
        'Polkon', 'Polmar', 'Pongratz', 'Pottinger', 'Primball', 'Pronar', 'PTM', 'Randob', 'RCM', 'Redos',
        'Reisch', 'Remet CNC Technology', 'Renault', 'Renders', 'Rimor', 'Rojo', 'Roland Tankbau', 'Rolfo',
        'Royen', 'Rubis', 'Rydwan', 'SACIM', 'SAM', 'Samro', 'SAN-CAR', 'Saris', 'Saxas', 'Scania',
        'Scheuerle', 'Schmidt', 'Schmitz Cargobull', 'Schrader', 'Schwarzmuller', 'Schwelmer Eisenwerk',
        'Scorpion', 'SDC', 'Serrus', 'Setra/Kaessbohrer', 'Sidecar', 'SLT Group', 'Sluis', 'Smit', 'Sommer',
        'Sor', 'Spier', 'Spitzer', 'Stadler', 'Star', 'Stas', 'Steelbro', 'Stema', 'Sterckeman', 'Sterling',
        'Stevens', 'STIM', 'Stokota', 'Stopexim', 'Strautmann', 'STT-SKIBICKI', 'Stürenberg', 'SVAN',
        'Swidnik TEMA', 'SWIFT', 'SYLAND', 'Syriusz', 'System Trailer', 'System Trailers', 'Szumlakowski',
        'TA-NO', 'Tabbert', 'Talson', 'TEC', 'Tecnokar', 'TEMARED', 'Thiel', 'THOMAS TRAILERS', 'Tigaro',
        'Tijhof', 'Tirsan', 'Tisvol', 'Titan', 'TOMPLAN', 'Trabosa', 'Tracon', 'TrailerTec', 'Trailis',
        'Trailor', 'Tramp Trail', 'Trax', 'Trigano', 'Trouillet', 'TSR', 'UMEGA', 'Unitrailer', 'UNSINN',
        'Ursus', 'VA', 'Valart', 'Van der Peet', 'Van Eck', 'Van Hool', 'Varmo', 'Veberti', 'VEGA TRAILER',
        'Veldhuizen', 'Vervetank', 'Viberti', 'Vlemmix', 'Vocol', 'Vogelzang', 'Volkswagen', 'Volvo',
        'Wabco', 'Wackenhut', 'WAF', 'Wagner', 'WALKLINER', 'Wark', 'Waryński', 'WBP Trailers',
        'WEB Trailer', 'Wecon', 'Weekend', 'WEEL', 'Weinsberg', 'Weippert', 'Welgro', 'Wellmeyer', 'Wena',
        'West', 'WESTERN', 'Westfalia', 'Wielton', 'Wijnveen', 'Wilex', 'Wilk', 'Wiola', 'WNP SUSKI',
        'Wohnmobil', 'Woodford', 'XXTrail', 'Zamarbu', 'Zaslaw', 'ZDT', 'ZKT', 'Zorzi', 'Zremb', 'Zwalve',
        'Özgül Trailer', 'Inne',
    ],
    AGRICULTURAL: [
        'Accord', 'Agco', 'Agrex', 'Agrimaster', 'AGRIPOL', 'Agrisem', 'AGRISTAL', 'Agro Factory',
        'AGRO-BARTONA', 'Agro-Instal', 'AGRO-KLON', 'Agro-Lift', 'Agro-Masz', 'AGRO-OSEK', 'Agro-tom',
        'Agrola', 'Agromet Mogilno', 'Agromex', 'AGROMILKA', 'Agrostoj Pelhrimov', 'Agrotechnology',
        'Aguirre', 'Akpil', 'Aksan Kardan', 'Allis', 'Alpego', 'Amazone', 'AMJ Agro', 'Annaburger',
        'ANTONIO CARRARO', 'APS', 'ARBOS', 'Ariens', 'Armor', 'AS MOTOR', 'Aupax', 'Ausa', 'Avant', 'Banrol',
        'Bargam', 'Basak', 'BAUER', 'BCS', 'BEDNAR', 'Befard', 'Belarus', 'Bergmann', 'Berthoud', 'Bielrol',
        'Bijlsma Hercules', 'Bizon', 'Blanchard', 'Bmhorse', 'Bobcat', 'Bobrujsk Agromasz', 'Bogballe',
        'Boguslav', 'Bomech', 'Bomet', 'Bonnel', 'Bourgoin', 'Brandi', 'Brantner', 'Braud', 'Bredal',
        'Breviglieri', 'Briri', 'Brochard', 'BURY', 'Caffini', 'Capello', 'Cargo', 'Carraro', 'CARRE',
        'Caruelle', 'Case IH', 'Casella', 'Caterpillar', 'Celli', 'Challenger', 'CHD', 'Checchi & Magli',
        'Claas', 'Claydon', 'CMT', 'Cochet', 'CORVUS', 'Craftsman', 'Crystal', 'Cub Cadet', 'Cynkomet',
        'Czajkowski', 'Damax', 'DAMMANN', 'Danfoil', 'David Brown', 'DCM', 'Debon', 'Del Morino',
        'Deutz-Fahr', 'Dewulf', 'Dexwal Bis', 'Dieci', 'Dominoni', 'DongFeng', 'Downs', 'Dubex',
        'ECOROBOTIX', 'Edlington', 'EkoPOM', 'EMMAROL', 'Empro', 'Enorossi', 'EUROMACCHINE', 'Eurotrac',
        'Everun', 'Evrard', 'Excat', 'Expom', 'Falc', 'Fantini', 'Faresin', 'Farmer', 'Farmet', 'FarmIQ',
        'Farmtech', 'Farmtrac', 'FELLA', 'Fendt', 'Feraboli', 'Ferju', 'Ferri', 'Fiat', 'Fimaks', 'Fiona',
        'Fliegl', 'Ford', 'FORST', 'Foton', 'Fotrak', 'Frisma', 'Gallignani', 'Gamatechnik', 'Gaspardo',
        'Gencsan Kardan', 'Geringhoff', 'Gianni Ferrari', 'Giant', 'Gleaner', 'Goldoni', 'Gomselmash',
        'Goweil', 'Grassrol', 'Great Plains', 'Gregoire Besson', 'Grimme', 'Gruse', 'Grutech',
        'GUNTER-GROSSMANN', 'Haith', 'Hako Werke', 'Hand-made', 'Hanomag', 'Hardi', 'Harmak', 'Hassia',
        'Hattat', 'Haybuster', 'HE-VA', 'Henart', 'Herbert', 'HEULING', 'Hinomoto', 'Hisarlar', 'Holaras',
        'Holder', 'Holmer', 'Honda', 'Horsch', 'Horus', 'Howard', 'HTZ', 'Hummel', 'Hurlimann', 'Husqvarna',
        'Hydramet', 'ICK', 'Idass', 'Ifa', 'IMANTS', 'Inter-tech', 'Intertech', 'IRUM', 'Iseki', 'Jar-met',
        'Jastech', 'JCB', 'John Deere', 'JOHN GREAVES', 'Joskin', 'Kaweco', 'Kemper', 'Keulmac', 'Kingway',
        'Kinshofer', 'Kioti', 'Kirong', 'Kirovets', 'KMK MASZYNY', 'Kobzarenko', 'KOMATSU', 'Kongskilde',
        'Koppl', 'Kowalski', 'Kraft', 'Kramer', 'Krone', 'Krpan', 'Krukowiak', 'KTS', 'Kuar', 'Kubota',
        'Kuhn', 'Kverneland', 'Köckerling', 'Lamborghini', 'Landini', 'Landstal', 'Langren', 'Laverda',
        'Leboulch', 'Lely', 'Lemken', 'Lemtech', 'Lisicki', 'LOCUST', 'Lovol', 'Lozova', 'LS Traktor',
        'M-ROL', 'Ma-Ag', 'Macks', 'Mahindra', 'Mandam', 'Manitou', 'MAR-POL', 'Marco Polo', 'Martin',
        'Marzia', 'Mascar', 'Maschio', 'Maschio Gaspardo', 'Massey Ferguson', 'MAT', 'Matermacc',
        'McCormick', 'McHale', 'Mecanica', 'Meprozet', 'Mercedes-Benz', 'Merlo', 'Metal Fach', 'Metal-Plast',
        'Metal-Technik', 'Miedema', 'Mitsubishi', 'Monosem', 'Moro Aratri', 'Moskit', 'MTZ', 'MultiOne',
        'Muthing', 'New Holland', 'Newtec', 'NEX', 'Nodet', 'Noremat', 'Okayama', 'Olimac', 'Opall Agri',
        'Orkan', 'Oros', 'Ozdoken', 'Ozduman', 'Pasquali', 'Peal', 'Perard', 'Peruzzo', 'Piast', 'Pichon',
        'POM Augustów', 'POM Ltd.', 'Pomarol', 'POMOT Chojna', 'Ponsse', 'Pottinger', 'Prokmar', 'Promagro',
        'Promar', 'Pronar', 'Quicke', 'Rabe', 'RAU', 'RAUCH', 'Regent', 'Remet CNC Technology', 'Remprodex',
        'Renault', 'Rivierre Casalis', 'Rivierre Greenland', 'RM', 'Roger', 'ROL-EX', 'Rolmako', 'ROPA',
        'Rostselmash', 'ROVATTI', 'Rumptstad', 'Ruris', 'SAM', 'SaMasz', 'Same', 'Samon', 'Sampo', 'Samson',
        'Sany', 'Sauerburger', 'Schaffer', 'Seguip', 'Sfoggia', 'Shibaura', 'SID', 'Sigma', 'SILOKING',
        'Simon', 'SIP', 'Sipma', 'SITREX', 'Sky', 'Sodimac', 'Sola', 'Solis', 'Someca', 'Sonarol',
        'Spearhead', 'Spider', 'Staltech', 'Stanhay', 'Steyer', 'Steyr', 'Stoll', 'Strautmann', 'Striegel',
        'Stroer', 'Sukov', 'Sulky', 'Supertino', 'Talex', 'TAXON', 'Tech-Project', 'Tecnoma', 'TEKNAMOTOR',
        'Tenias', 'Thaler', 'Tierre', 'Tolmet', 'Tong', 'TOSCANO', 'TOZAMET', 'TracLift', 'Trioliet', 'Tume',
        'Tutkun', 'TYM', 'UMEGA', 'Unia', 'Uniforest', 'Universal', 'Unlu', 'Ursus', 'UTB', 'Valmet',
        'Valpadana', 'Valtec', 'Valtra', 'Veles Agro', 'Veles Alt', 'Vermeer', 'Vicon', 'Vogel&Noot',
        'Volvo', 'Väderstad', 'Weidemann', 'Welger', 'WESTERN', 'Weycor', 'Wiedenmann', 'Wielton', 'Wizard',
        'Wolagri', 'Woprol', 'Yanmar', 'Yaroslavich', 'Zanila', 'ZDT', 'Zetor', 'Överum', 'Inne',
    ],
};

export const MODELS_BY_CATEGORY: Partial<Record<VehicleCategory, Record<string, readonly string[]>>> = {
    PASSENGER: {
        Abarth: [
            '124', '500', '500Ce', '500e', '595', '595C', '600e', '695', '695C', 'Grande Punto', 'Punto Evo',
            'Inny',
        ],
        Acura: [
            'CL', 'Integra', 'Legend', 'MDX', 'NSX', 'RDX', 'RL', 'RSX', 'TL', 'TLX', 'TSX', 'Vigor', 'ZDX',
            'Inny',
        ],
        Aito: ['M9', 'Inny'],
        Aiways: ['U5', 'U6'],
        Aixam: [
            'A721', 'A741', 'A751', 'City', 'Coupe', 'Crossline', 'Crossover', 'GTO', 'Mega', 'Roadline',
            'Scouty', 'Scouty R', 'Inny',
        ],
        'Alfa Romeo': [
            '145', '146', '147', '155', '156', '156 Sportwagon', '159', '159 Sportwagon', '164', '166', '33',
            '33 Sportwagon', '4C', '75', '90', 'Alfasud', 'Alfetta', 'Brera', 'Crosswagon', 'Giulia',
            'Giulietta', 'GT', 'GTV', 'Junior', 'Mito', 'RS', 'Spider', 'Sportwagon', 'Sprint', 'Stelvio',
            'Tonale', 'Inny',
        ],
        Alpine: ['A110', 'A290', 'A390', 'Inny'],
        Arcfox: ['Alpha S5', 'Alpha-S', 'Alpha-T', 'Kaola'],
        Ariel: ['Atom', 'Nomad', 'Inny'],
        Artega: ['GT'],
        Asia: ['Rocsta'],
        'Aston Martin': [
            'Bulldog', 'Cygnet', 'DB', 'DB Mk III', 'DB1', 'DB11', 'DB12', 'DB2', 'DB4', 'DB5', 'DB6', 'DB7',
            'DB9', 'DBS', 'DBS Superleggera', 'DBX', 'DBX707', 'Lagonda', 'One-77', 'Rapide', 'V12 Vanquish',
            'V12 Vantage', 'V8', 'V8 Vantage', 'V8 Zagato', 'Vanquish', 'Vantage', 'Virage', 'Volatne',
            'Inny',
        ],
        Audi: [
            '100', '100 Avant', '200', '200 Avant', '80', '80 Avant', '90', 'A1 3-drzwiowe', 'A1 Allstreet',
            'A1 Citycarver', 'A1 Sportback', 'A2', 'A2 e-tron', 'A3 3-drzwiowe', 'A3 Allstreet', 'A3 Cabrio',
            'A3 Limousine', 'A3 Sportback', 'A4 Allroad', 'A4 Avant', 'A4 Cabrio', 'A4 Limousine',
            'A5 Avant', 'A5 Cabrio', 'A5 Coupé', 'A5 Limousine', 'A5 Sportback', 'A6 Allroad', 'A6 Avant',
            'A6 Avant e-tron', 'A6 Limousine', 'A6 Sportback e-tron', 'A7 Sportback', 'A8', 'Cabriolet',
            'Coupe', 'e-tron', 'e-tron GT', 'e-tron Sportback', 'E5 Sportback', 'Q2', 'Q3', 'Q3 Sportback',
            'Q4 e-tron', 'Q4 Sportback e-tron', 'Q5', 'Q5 Sportback', 'Q6 e-tron', 'Q6 Sportback e-tron',
            'Q7', 'Q8', 'Q8 e-tron', 'Q8 Sportback e-tron', 'Q9', 'Quattro', 'R8 Coupé', 'R8 Spyder',
            'RS e-tron GT', 'RS Q3', 'RS Q3 Sportback', 'RS Q8', 'RS2', 'RS3 Limousine', 'RS3 Sportback',
            'RS4 Avant', 'RS4 Cabrio', 'RS4 Limousine', 'RS5 Avant', 'RS5 Cabrio', 'RS5 Coupé',
            'RS5 Limousine', 'RS5 Sportback', 'RS6', 'RS6 Avant', 'RS7 Sportback', 'S1', 'S1 Sportback',
            'S2', 'S3', 'S3 Cabrio', 'S3 Limousine', 'S3 Sportback', 'S4 Avant', 'S4 Cabrio', 'S4 Limousine',
            'S5 Avant', 'S5 Cabrio', 'S5 Coupé', 'S5 Limousine', 'S5 Sportback', 'S6 Avant',
            'S6 Avant e-tron', 'S6 Limousine', 'S6 Sportback e-tron', 'S7 Sportback', 'S8', 'SQ2', 'SQ5',
            'SQ5 Sportback', 'SQ6', 'SQ6 e-tron', 'SQ6 Sportback e-tron', 'SQ7', 'SQ8', 'SQ8 e-tron', 'SQ9',
            'TT Coupé', 'TT Roadster', 'TT RS Coupé', 'TT RS Roadster', 'TT S Coupé', 'TT S Roadster', 'V8',
            'Inny',
        ],
        Austin: ['Allegro', 'Ambasador', 'Healey', 'Maxi', 'Metro', 'Mini', 'Montego', 'Inny'],
        Autobianchi: ['A112', 'Bianchina'],
        AVATR: ['11', '12', '7'],
        BAIC: [
            '3', '5', '7', 'B40', 'BJ20', 'BJ30', 'BJ40', 'BJ60', 'D20', 'Senova X25', 'Senova X35',
            'Senova X55', 'Senova X65', 'X3', 'X5', 'X7', 'X75', 'Inny',
        ],
        Bajaj: ['Qute'],
        BAW: ['212', 'Brumby', 'E6', 'E7', 'Hiace', 'MPV', 'Pony', 'Inny'],
        Bentley: [
            'Arnage', 'Azure', 'Bentayga', 'Brooklands', 'Continental GT', 'Eight', 'Flying Spur',
            'Mulsanne', 'Turbo R', 'Turbo RT', 'Turbo S', 'Inny',
        ],
        Bentu: ['BTE05', 'Inny'],
        Bestune: ['B70', 'B90', 'T77', 'T90'],
        Biro: ['Big', 'Small'],
        Blaval: ['Solar 2'],
        BMW: [
            '1M', '3GT', '5GT', '6GT', 'i3', 'i4', 'i5', 'i7', 'i8', 'iX', 'iX1', 'iX2', 'iX3', 'M2', 'M3',
            'M4', 'M5', 'M6', 'M8', 'Seria 1', 'Seria 2', 'Seria 3', 'Seria 4', 'Seria 5', 'Seria 6',
            'Seria 7', 'Seria 8', 'X1', 'X2', 'X3', 'X3 M', 'X4', 'X4 M', 'X5', 'X5 M', 'X6', 'X6M', 'X7',
            'XM', 'Z1', 'Z3', 'Z4', 'Z4 M', 'Z8', 'Inny',
        ],
        'BMW-ALPINA': [
            'B10', 'B12', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'D10', 'D3', 'D4', 'D5', 'Roadster S', 'XB7',
            'XD3', 'XD4', 'Inny',
        ],
        Brilliance: ['BC3', 'BS2', 'BS4', 'BS6', 'Inny'],
        Bugatti: ['Chiron', 'Divo', 'EB 110', 'Veyron', 'Inny'],
        Buick: [
            'Centurion', 'Century', 'Electra', 'Enclave', 'Encore', 'Lacrosse', 'Le Sabre', 'Lucerne',
            'Park Avenue', 'Reatta', 'Regal', 'Rendezvous', 'Riviera', 'Roadmaster', 'Skyhawk', 'Skylark',
            'Inny',
        ],
        BYD: [
            'Atto 2', 'Atto 2 DM-i', 'Atto 3', 'Dolphin', 'Dolphin G', 'Dolphin Mini', 'Dolphin Surf', 'e2',
            'Han', 'Han L', 'Leopard 3', 'Leopard 5', 'Leopard 7', 'Leopard 8', 'Qin', 'Seagull', 'Seal',
            'Seal 5', 'Seal 6', 'Seal U', 'Sealion 5', 'Sealion 7', 'Shark', 'Shark 6', 'Song', 'Tang',
            'Tang L', 'Xia', 'Yangwang U7', 'Yangwang U8', 'Yangwang U9', 'Yuan', 'Inny',
        ],
        Cadillac: [
            'Allante', 'ATS', 'BLS', 'Brougham', 'Catera', 'Cimarron', 'CT4', 'CT5', 'CT6', 'CTS', 'Deville',
            'DTS', 'Eldorado', 'ELR', 'Escalade', 'Fleetwood', 'LYRIQ', 'Seville', 'SLS', 'SRX', 'STS',
            'STS-V', 'XLR', 'XLR-V', 'XT4', 'XT5', 'XT6', 'XTS', 'Inny',
        ],
        Casalini: ['Kerry', 'M10', 'M12', 'M14', 'M14 2.0', 'Pickup', 'Sulky', 'Ydea', 'Inny'],
        Caterham: ['Academy', 'CSR', 'Roadsport', 'Seven', 'Super Seven', 'Inny'],
        Cenntro: ['Avantier', 'Inny'],
        Changan: ['CS55 Plus', 'CS75 Plus', 'Deepal S05', 'Deepal S07', 'UNI-K', 'UNI-T', 'UNI-V'],
        Chatenet: [
            'CH22 Barooder', 'CH26', 'CH30', 'CH32', 'CH40', 'CH46', 'Media', 'Speedino', 'Sporteevo',
            'Stella', 'Inny',
        ],
        Chery: ['Arrizo 5', 'Arrizo 8', 'Tiggo 4', 'Tiggo 7', 'Tiggo 8', 'Tiggo 9'],
        'Chery Fulwin': ['A8', 'A9L', 'T10', 'T11', 'T8', 'T9'],
        Chevrolet: [
            '1500', '2500', '3500', 'Alero', 'Apache', 'Astro', 'Avalanche', 'Aveo', 'Bel Air', 'Beretta',
            'Blazer', 'Bolt', 'C-10', 'C-20', 'C-30', 'Camaro', 'Caprice', 'Captiva', 'Cavalier',
            'Celebrity', 'Chevelle', 'Chevy Van', 'Citation', 'Cobalt', 'Colorado', 'Corsica', 'Corvair',
            'Corvette', 'Cruze', 'El Camino', 'Epica', 'Equinox', 'Evanda', 'Express', 'G', 'HHR', 'Impala',
            'K1500', 'K30', 'Kalos', 'Lacetti', 'Lumina', 'Malibu', 'Matiz', 'Menlo', 'Monte Carlo', 'Monza',
            'Nova', 'Nubira', 'Orlando', 'Rezzo', 'S-10', 'Silverado', 'Spark', 'Spectrum', 'SS', 'SSR',
            'Suburban', 'Tacuma', 'Tahoe', 'Trailblazer', 'Trans Sport', 'Traverse', 'Trax', 'Venture',
            'Volt', 'Inny',
        ],
        Chrysler: [
            '200', '300', '300C', '300M', '300s', 'Aspen', 'Caravan', 'Concorde', 'Crossfire', 'Daytona',
            'ES', 'Grand Voyager', 'GS', 'GTS', 'Le Baron', 'LHS', 'Neon', 'New Yorker', 'Pacifica',
            'Prowler', 'PT Cruiser', 'Saratoga', 'Sebring', 'Stratus', 'Town & Country', 'Valiant', 'Viper',
            'Vision', 'Voyager', 'Inny',
        ],
        Citroen: [
            '2 CV', 'Ami', 'AX', 'Axel', 'Berlingo', 'BX', 'C-Crosser', 'C-Elysée', 'C-Zero', 'C1', 'C2',
            'C3', 'C3 Aircross', 'C3 Picasso', 'C3 Pluriel', 'C4', 'C4 Aircross', 'C4 Cactus',
            'C4 Grand Picasso', 'C4 Picasso', 'C4 SpaceTourer', 'C4X', 'C5', 'C5 Aircross', 'C5X', 'C6',
            'C8', 'CX', 'DS', 'DS3', 'DS4', 'DS5', 'DS7', 'E-Mehari', 'Evasion', 'GSA', 'Jumper', 'Jumpy',
            'Jumpy Combi', 'Nemo', 'Saxo', 'SM', 'SpaceTourer', 'Visa', 'Xantia', 'XM', 'Xsara',
            'Xsara Picasso', 'ZX', 'Inny',
        ],
        Cupra: [
            'Ateca', 'Born', 'Formentor', 'Leon', 'Leon Sportstourer', 'Raval', 'Tavascan', 'Terramar',
            'Inny',
        ],
        Dacia: [
            '1300', '1307', '1310', '1400', '1410', 'Bigster', 'Dokker', 'Dokker Van', 'Duster', 'Jogger',
            'Lodgy', 'Logan', 'Logan Van', 'Nova', 'Pick Up', 'Sandero', 'Sandero Stepway', 'Solenza',
            'Spring', 'Super Nova', 'Inny',
        ],
        Daewoo: [
            'Chairman', 'Cielo', 'Espero', 'Evanda', 'Kalos', 'Korando', 'Lacetti', 'Lanos', 'Leganza',
            'Matiz', 'Musso', 'Nexia', 'Nubira', 'Racer', 'Rezzo', 'Tacuma', 'Tico', 'Inny',
        ],
        Daihatsu: [
            'Applause', 'Charade', 'Charmant', 'Copen', 'Cuore', 'Feroza', 'Fourtrak', 'Freeclimber',
            'Gran Move', 'Hijet', 'Materia', 'Move', 'Rocky', 'Sirion', 'Sportrak', 'Terios', 'Trevis',
            'YRV', 'Inny',
        ],
        DEEPAL: ['G318', 'L07', 'S05', 'S07', 'S09'],
        DeLorean: ['DMC-12'],
        Denza: ['B5', 'B8', 'D9', 'N7', 'N8', 'N8L', 'N9', 'Z9', 'Z9 GT', 'Inny'],
        DFM: ['Forthing 4', 'Forthing 5'],
        DFSK: [
            'Double Cab', 'e5', 'Fengon 5', 'Fengon 500', 'Fengon 580', 'Fengon 7', 'Forthing 3',
            'Forthing 5', 'FX600', 'Glory 580', 'Mini Bus', 'Mini Van', 'Pick Up', 'Seres 3', 'Seres 5',
            'T5 Evo',
        ],
        DKW: ['Inny'],
        Dodge: [
            'Avenger', 'Caliber', 'Caravan', 'Challenger', 'Charger', 'Dakota', 'Dart', 'Daytona',
            'Diplomat', 'Durango', 'Dynasty', 'Grand Caravan', 'Hornet', 'Intrepid', 'Journey', 'Magnum',
            'Monaco', 'Neon', 'Nitro', 'Omni', 'RAM', 'RAM TRX', 'Spirit', 'Stealth', 'Stratus', 'Viper',
            'Inny',
        ],
        Dongfeng: ['AX7', 'Box', 'Huge', 'M-Hero 917', 'Mage', 'Shine', 'Shine GS', 'Vigo', 'Inny'],
        'DR MOTOR': [
            'DR 1', 'DR 3', 'DR 5', 'DR 6', 'EVO CROSS 4', 'EVO CUATRO', 'PK8', 'TIGER EIGHT', 'TIGER SIX',
            'Inny',
        ],
        'DS Automobiles': [
            'DS 3', 'DS 3 Crossback', 'DS 4', 'DS 4 Crossback', 'DS 5', 'DS 7', 'DS 7 Crossback', 'DS 9',
            'N°4', 'N°7', 'N°7 E-TENSE', 'N°8', 'Inny',
        ],
        'e.GO': ['e.wave X', 'Life 20', 'Life 40', 'Life 60', 'Inny'],
        Elaris: ['BEO', 'DYO', 'JACO', 'Lenn', 'LEO', 'Pio', 'Inny'],
        Eletroride: ['Futuri 4'],
        Exlantix: ['ES', 'ET'],
        FAW: ['HQ'],
        Ferrari: [
            '12Cilindri', '208', '248', '250', '288', '296 GTB', '296 GTS', '308', '328', '330', '348',
            '360', '365', '400', '412', '456', '458 Italia', '458 Speciale', '488', '488 Pista',
            '488 Pista Spider', '512', '575', '599GTB', '612', '750', '812 GTS', '812 Superfast', 'Amalfi',
            'California', 'California T', 'Daytona', 'Daytona SP3', 'Dino GT4', 'Enzo', 'F12berlinetta',
            'F355', 'F360', 'F40', 'F430', 'F50', 'F550', 'F8 Spider', 'F8 Tributo', 'FF', 'GTC4Lusso',
            'LaFerrari', 'Mondial', 'Portofino', 'Portofino M', 'Purosangue', 'Roma', 'Roma Spider',
            'SF90 Spider', 'SF90 Stradale', 'Superamerica', 'Testarossa', 'Inny',
        ],
        Fiat: [
            '124', '124 Spider', '125p', '126', '127', '128', '130', '131', '132', '500', '500e', '500L',
            '500S', '500X', '600', '850', 'Albea', 'Barchetta', 'Brava', 'Bravo', 'Cinquecento', 'Coupe',
            'Croma', 'Dino', 'Doblo', 'Ducato', 'Fiorino', 'Freemont', 'Fullback', 'Grande Panda',
            'Grande Punto', 'Idea', 'Linea', 'Marea', 'Multipla', 'Palio', 'Panda', 'Pandina', 'Punto',
            'Punto 2012', 'Punto Evo', 'Qubo', 'Regata', 'Ritmo', 'Scudo', 'Sedici', 'Seicento', 'Siena',
            'Spider Europa', 'Stilo', 'Strada', 'Talento', 'Tempra', 'Tipo', 'Ulysse', 'Uno', 'X 1', 'Inny',
        ],
        Fisker: ['EMotion', 'Karma', 'Ocean', 'Pear', 'Inny'],
        Ford: [
            'Aerostar', 'Aspire', 'B-MAX', 'Bronco', 'Bronco Sport', 'C-MAX', 'Capri', 'Contour', 'Cougar',
            'Courier', 'Crown', 'E-Tourneo Courier', 'E-Tourneo Custom', 'E-Transit', 'E-Transit Custom',
            'Econoline', 'Econovan', 'EcoSport', 'Edge', 'Escape', 'Escort', 'Excursion', 'Expedition',
            'Explorer', 'F150', 'F250', 'F350', 'Fairlane', 'Falcon', 'Festiva', 'Fiesta', 'FIVE HUNDRED',
            'Flex', 'Focus', 'Focus C-Max', 'Focus CC', 'Focus SW', 'Freestar', 'Freestyle', 'Fusion',
            'Galaxy', 'Granada', 'Grand C-MAX', 'GT', 'KA', 'Ka+', 'Kuga', 'Maverick', 'Mercury', 'Mondeo',
            'Mondeo SW', 'Mustang', 'Mustang Mach-E', 'Orion', 'Probe', 'Puma', 'Puma Gen-E', 'Ranchero',
            'Ranger', 'Ranger Raptor', 'S-Max', 'Scorpio', 'Sierra', 'Streetka', 'Taunus', 'Taurus', 'Tempo',
            'Thunderbird', 'Tourneo Connect', 'Tourneo Connect Grand', 'Tourneo Courier', 'Tourneo Custom',
            'Transit', 'Transit Connect', 'Transit Courier', 'Transit Custom', 'Windstar', 'Inny',
        ],
        Forthing: ['S7 REEV', 'T5 EVO', 'U Tour', 'V-Tour', 'Inny'],
        FOTON: ['eTUNLAND', 'TUNLAND G7', 'TUNLAND V', 'Inny'],
        GAC: ['AION UT', 'AION V', 'AION Y', 'Emkoo', 'Emzoom', 'Hyptec HT'],
        Gaz: ['67', '69', 'Inny'],
        Geely: [
            'Atlas II', 'Coolray', 'Emgrand', 'EX5', 'EX5 EM-i', 'Galaxy', 'Galaxy L7', 'M9', 'Monjaro',
            'New Coolray', 'Okavango', 'Starray', 'Tugella', 'Xplore 125', 'Inny',
        ],
        Genesis: ['Electrified G80', 'Electrified GV70', 'G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'Inny'],
        GMC: [
            'Acadia', 'Canyon', 'Envoy', 'Hummer', 'Safari', 'Savana', 'Sierra', 'Sonoma', 'Syclone',
            'Terrain', 'Typhoon', 'Vandura', 'Yukon', 'Inny',
        ],
        GWM: ['Hover', 'Ora 03', 'Ora 07', 'Ora 5', 'Tank 300', 'Tank 500', 'Wey 03', 'Wey 05', 'Inny'],
        HiPhi: ['A', 'X', 'Y', 'Z'],
        Honda: [
            'Accord', 'Aerodeck', 'City', 'Civic', 'Clarity', 'Concerto', 'CR-V', 'CR-Z', 'CRX', 'e',
            'e:NP1', 'e:NSP1', 'e:NY1', 'Element', 'Fit', 'FR-V', 'HR-V', 'Insight', 'Integra', 'Jazz',
            'Legend', 'Logo', 'NSX', 'Odyssey', 'Passport', 'Pilot', 'Prelude', 'Ridgeline', 'S 2000',
            'Shuttle', 'Stream', 'ZR-V', 'Inny',
        ],
        Hongqi: ['E-HS9', 'H5', 'H6', 'H7', 'H9', 'HS3', 'HS5', 'HS7', 'Inny'],
        Hummer: ['H1', 'H2', 'H3', 'Inny'],
        Hyundai: [
            'Accent', 'Atos', 'Avante', 'Azera', 'Bayon', 'Coupe', 'Elantra', 'Equus', 'Excel', 'Galloper',
            'Genesis', 'Genesis Coupe', 'Getz', 'Grand Santa Fe', 'Grandeur', 'H-1', 'H-1 Starex', 'H200',
            'H350', 'i10', 'i20', 'i25', 'i30', 'i30 N', 'i40', 'Inster', 'IONIQ', 'IONIQ 5', 'IONIQ 6',
            'IONIQ 7', 'IONIQ 9', 'ix20', 'ix35', 'ix55', 'Kona', 'Lantra', 'Matrix', 'NEXO', 'Palisade',
            'Pony', 'S-Coupe', 'Santa Cruz', 'Santa Fe', 'Santamo', 'Sonata', 'Sonica', 'Staria', 'Terracan',
            'Trajet', 'Tucson', 'Veloster', 'Veracruz', 'XG 30', 'XG 350', 'Inny',
        ],
        iamelectric: ['ARIEL4', 'SHARK'],
        'ICH-X': ['K2', 'K3'],
        Ineos: ['Grenadier', 'Quartermaster', 'Inny'],
        Infiniti: [
            'EX', 'FX', 'G', 'I30', 'I35', 'J30', 'M', 'Q30', 'Q45', 'Q50', 'Q60', 'Q70', 'QX', 'QX30',
            'QX50', 'QX55', 'QX60', 'QX70', 'QX80', 'Inny',
        ],
        Isuzu: ['Campo', 'D-Max', 'Gemini', 'Midi', 'Pick up', 'Trooper', 'Inny'],
        Iveco: ['Daily', 'Massif', 'Inny'],
        JAC: [
            'e-J7', 'e-JS1', 'e-JS4', 'J6', 'J7', 'JS2', 'JS3', 'JS4', 'JS6', 'JS7', 'JS8', 'RF8', 'T6',
            'T8 PRO', 'T9',
        ],
        Jaecoo: ['5', '6', '7', '8', '9', 'E5', 'V23', 'Inny'],
        Jaguar: [
            'Daimler', 'E-Pace', 'E-Type', 'F-Pace', 'F-Type', 'I-Pace', 'MK II', 'S-Type', 'X-Type', 'XE',
            'XF', 'XJ', 'XJR', 'XJS', 'XK', 'XK8', 'Inny',
        ],
        Jeep: [
            'Avenger', 'Cherokee', 'CJ', 'Comanche', 'Commander', 'Compass', 'Gladiator', 'Grand Cherokee',
            'Grand Wagoneer', 'Liberty', 'Patriot', 'Renegade', 'Wagoneer', 'Willys', 'Wrangler', 'Inny',
        ],
        Jetour: ['Dashing', 'G700', 'T2', 'Traveller', 'X70', 'X70 Plus', 'X90', 'X95'],
        Jinpeng: ['Ami', 'Inny'],
        Kia: [
            'Asia Rocsta', 'Besta', 'Cadenza', 'Carens', 'Carnival', 'Ceed', 'Cerato', 'Clarus', 'Elan',
            'EV2', 'EV3', 'EV4', 'EV5', 'EV6', 'EV9', 'Joice', 'K4', 'K5', 'K9', 'Leo', 'Magentis', 'Mentor',
            'Niro', 'Opirus', 'Optima', 'Picanto', 'Pregio', 'Pride', 'ProCeed', 'PV5', 'Retona', 'Rio',
            'Roadster', 'Rocsta', 'Sedona', 'Seltos', 'Sephia', 'Shuma', 'Sorento', 'Soul', 'Spectra',
            'Sportage', 'Stinger', 'Stonic', 'Tasman', 'Telluride', 'Venga', 'XCeed', 'Inny',
        ],
        KTM: ['X-BOW'],
        Lada: [
            '110', '111', '1117', '1118', '1119', '112', '1200', '1300', '1500', '2101', '2103', '2104',
            '2105', '2106', '2107', '2108', '2109', '2110', '2111', '2112', '2170', 'Aleko', 'Forma',
            'Granta', 'Kalina', 'Niva', 'Nova', 'Priora', 'Samara', 'Inny',
        ],
        Lamborghini: [
            'Aventador', 'Countach', 'Diablo', 'Espada', 'Gallardo', 'Huracan', 'Jalpa', 'LM', 'Miura',
            'Murcielago', 'Revuelto', 'Temerario', 'Urraco', 'Urus', 'Inny',
        ],
        Lancia: [
            'Beta', 'Dedra', 'Delta', 'Flamina', 'Fulvia', 'Gamma', 'Kappa', 'Lybra', 'Musa', 'Phedra',
            'Prisma', 'Stratos', 'Thema', 'Thesis', 'Voyager', 'Ypsilon', 'Zeta', 'Inny',
        ],
        'Land Rover': [
            'Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover', 'Range Rover Evoque',
            'Range Rover Sport', 'Range Rover Velar', 'Inny',
        ],
        Leapmotor: ['B03X', 'B05', 'B10', 'C01', 'C10', 'C11', 'C16', 'T03', 'Inny'],
        LEVC: ['TX'],
        Lexus: [
            'CT', 'ES', 'GS', 'GS F', 'GX', 'HS 250h', 'IS', 'LBX', 'LC', 'LFA', 'LM', 'LS', 'LX', 'NX',
            'RC', 'RX', 'RZ', 'SC', 'TX', 'UX', 'Inny',
        ],
        Li: ['L6', 'L7', 'L8', 'L9', 'Mega', 'Inny'],
        Ligier: [
            'Altul', 'Ambra', 'Be-Two', 'Be-Up', 'IXO', 'JS RC', 'JS49', 'JS50', 'JS50L', 'JS60', 'Nova',
            'Optima', 'X-Too', 'X-Too Max', 'X-Too R', 'X-Too RS', 'X-Too S', 'Inny',
        ],
        Lincoln: [
            'Aviator', 'Continental', 'Corsair', 'LS', 'Mark', 'Mark LT', 'MKC', 'MKX', 'MKZ', 'Nautilus',
            'Navigator', 'Town Car', 'Inny',
        ],
        Lixiang: ['L7', 'L9'],
        Lotus: [
            '340R', 'Cortina', 'Elan', 'Eletre', 'Elise', 'Elite', 'Emeya', 'Emira', 'Esprit', 'Europa',
            'Evora', 'Excel', 'Exige', 'Super Seven', 'V8', 'Inny',
        ],
        LTI: ['Fairway', 'TX2', 'TX4', 'Inny'],
        Lucid: ['Air', 'Gravity', 'Inny'],
        'Lynk & Co': ['01', '02', '03', '900', 'Inny'],
        Maextro: ['S800', 'Inny'],
        MAN: ['TGE', 'Inny'],
        Maserati: [
            '224', '3200', 'Biturbo', 'Coupe', 'Ghibli', 'GranCabrio', 'Gransport', 'GranTurismo', 'Grecale',
            'Levante', 'MC20', 'MC20 Cielo', 'Merak', 'Quattroporte', 'Shamal', 'Spyder', 'Inny',
        ],
        Maxus: ['eT90', 'Euniq 5', 'Euniq 6', 'MIFA 9', 'Inny'],
        Maybach: ['57', '62', 'Inny'],
        Mazda: [
            '121', '2', '2 Hybrid', '3', '323', '323F', '5', '6', '626', '6e', '929', 'Bongo', 'BT-50',
            'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-60', 'CX-7', 'CX-70', 'CX-80', 'CX-9', 'CX-90', 'Demio',
            'EZ-6', 'EZ-60', 'Millenia', 'MPV', 'MX-3', 'MX-30', 'MX-5', 'MX-6', 'Premacy', 'Protege',
            'RX-6', 'RX-7', 'RX-8', 'Seria B', 'Seria E', 'Tribute', 'Xedos', 'Xedos 9', 'Inny',
        ],
        McLaren: [
            '570 GT', '570S Coupe', '570S Spider', '600LT Coupe', '600LT Spider', '650S', '675Lt',
            '720S Coupe', '720S Spider', '750S', '765LT Coupe', '765LT Spider', 'altul', 'Artura', 'GT',
            'MP4-12C', 'Inny',
        ],
        Melex: ['391'],
        'Mercedes-Benz': [
            '280', 'AMG GT', 'Citan', 'CL', 'CLA', 'CLC', 'CLE', 'CLK', 'CLS', 'EQA', 'EQB', 'EQC', 'EQE',
            'EQS', 'EQS 680 SUV', 'EQT', 'EQV', 'GL', 'GLA', 'GLB', 'GLC', 'GLE', 'GLK', 'GLS', 'Klasa A',
            'Klasa B', 'Klasa C', 'Klasa E', 'Klasa G', 'Klasa R', 'Klasa S', 'Klasa T', 'Klasa V',
            'Klasa X', 'Marco Polo', 'Maybach GLS', 'Maybach Klasa S', 'Maybach SL 680', 'MB 100', 'ML',
            'Monarch', 'SL', 'SLC', 'SLK', 'SLR', 'SLS', 'Sprinter', 'Vaneo', 'Vario', 'Viano', 'Vito',
            'VLE', 'W111', 'W123', 'W124 (1984-1993)', 'W201 (190)', 'Inny',
        ],
        Mercury: [
            'Comet', 'Cougar', 'Marauder', 'Mariner', 'Marquis', 'Milan', 'Montego', 'Monterey',
            'Mountaineer', 'Sable', 'Tracer', 'Villager', 'Zephyr', 'Inny',
        ],
        MG: [
            '4', '5', '7', 'Cyberster', 'HS', 'HS Hybrid+', 'HS PHEV', 'Marvel R', 'MG3', 'MGB', 'MGF',
            'Midget', 'S5 EV', 'S6', 'S9', 'TF', 'ZR', 'ZS', 'ZS Hybrid+', 'ZT', 'Inny',
        ],
        Microcar: [
            'Cargo', 'DUE', 'DUE First', 'Flex', 'Highland X', 'Ligier', 'M.Cross', 'M.GO', 'MC', 'Virgo',
            'Inny',
        ],
        Mini: [
            '1000', '1300', 'Aceman', 'Clubman', 'Cooper', 'Cooper S', 'Countryman', 'John Cooper Works',
            'ONE', 'Paceman', 'Inny',
        ],
        Mitsubishi: [
            '3000GT', 'ASX', 'Canter', 'Carisma', 'Colt', 'Cordia', 'Cosmos', 'Diamante', 'Eclipse',
            'Eclipse Cross', 'Endeavor', 'FTO', 'Galant', 'Galloper', 'Grandis', 'i-MiEV', 'L200', 'L300',
            'L400', 'Lancer', 'Lancer Evolution', 'Montero', 'Outlander', 'Pajero', 'Pajero Pinin',
            'Pajero Sport', 'Santamo', 'Sapporo', 'Sigma', 'Space Gear', 'Space Runner', 'Space Star',
            'Space Wagon', 'Starion', 'Tredia', 'Inny',
        ],
        Morgan: ['Plus Four', 'Super 3', 'Supersport', 'Inny'],
        NIO: ['el7', 'et5', 'et7'],
        Nissan: [
            '100 NX', '200 SX', '240 SX', '280 ZX', '300 ZX', '350 Z', '370 Z', '400 Z', 'Almera',
            'Almera Tino', 'Altima', 'Ariya', 'Armada', 'Bluebird', 'Cherry', 'Cube', 'Frontier', 'GT-R',
            'Interstar', 'Juke', 'Kikcs', 'King Cab', 'Kubistar', 'Laurel', 'Leaf', 'Maxima', 'Micra',
            'Murano', 'Navara', 'Note', 'NP300 Pickup', 'NV200', 'NV300', 'NV400', 'Pathfinder', 'Patrol',
            'Pickup', 'Pixo', 'Prairie', 'Primastar', 'Primera', 'Pulsar', 'Qashqai', 'Qashqai+2', 'Quest',
            'Rogue', 'Sentra', 'Serena', 'Silvia', 'Skyline', 'Stanza', 'Sunny', 'Terrano', 'Tiida', 'Titan',
            'Townstar', 'Trade', 'Urvan', 'Vanette', 'X-Trail', 'Xterra', 'Inny',
        ],
        Nysa: ['Seria 500', 'Seria N', 'Inny'],
        Oldsmobile: [
            'Alero', 'Aurora', 'Bravada', 'Custom Cruiser', 'Cutlass', 'Delta 88', 'Eighty - Eight',
            'Intrigue', 'Regency', 'Silhouette', 'Supreme', 'Toronado', 'Inny',
        ],
        Omoda: ['11', '5', '7', '9', 'E5', 'Inny'],
        Opel: [
            'Adam', 'Agila', 'Ampera', 'Antara', 'Arena', 'Ascona', 'Astra', 'Calibra', 'Campo', 'Cascada',
            'Combo', 'Commodore', 'Corsa', 'Crossland', 'Crossland X', 'Diplomat', 'Frontera', 'Grandland',
            'Grandland X', 'GT', 'Insignia', 'Kadett', 'Karl', 'Manta', 'Meriva', 'Mokka', 'Mokka X',
            'Monterey', 'Monza', 'Movano', 'Nova', 'Omega', 'Pick up Sportcap', 'Rekord', 'Rocks-e',
            'Senator', 'Signum', 'Sintra', 'Speedster', 'Tigra', 'Vectra', 'Vivaro', 'Zafira', 'Inny',
        ],
        Peugeot: [
            '1007', '104', '106', '107', '108', '2008', '204', '205', '206', '206 CC', '206 plus', '207',
            '207 CC', '208', '3008', '301', '304', '305', '306', '307', '307 CC', '308', '308 CC', '309',
            '4007', '4008', '404', '405', '406', '407', '408', '5008', '504', '505', '508', '604', '605',
            '607', '806', '807', 'Bipper', 'Boxer', 'E-5008', 'Expert', 'iOn', 'Partner', 'RCZ', 'Rifter',
            'Traveller', 'Inny',
        ],
        Piaggio: ['Porter', 'Inny'],
        Plymouth: [
            'Belvedere', 'Caravelle', 'Duster', 'Fury', 'Gran Fury', 'Grand Voyager', 'GTX', 'Horizon',
            'Laser', 'Prowler', 'Road Runner', 'Satellite', 'Superbird', 'Turismo', 'Valiant', 'Voyager',
            'Inny',
        ],
        Polestar: ['1', '2', '3', 'Inny'],
        Polonez: ['1.5', '1.6', 'Atu', 'Caro', 'Inny'],
        Pontiac: [
            '1000', '6000', 'Bonneville', 'Catalina', 'Chieftain', 'Fiero', 'Firebird', 'G6', 'Grand-Am',
            'Grand-Prix', 'GTO', 'Le Mans', 'Montana', 'Solstice', 'Sunbird', 'Sunfire', 'Trans Am',
            'Trans Sport', 'Vibe', 'Inny',
        ],
        Porsche: [
            '356', '718 Boxster', '718 Cayman', '718 Spyder', '911', '912', '914', '924', '928', '944',
            '959', '962', '968', 'Boxster', 'Carrera GT', 'Cayenne', 'Cayenne Electric', 'Cayman', 'Macan',
            'Panamera', 'Taycan', 'Inny',
        ],
        RAM: ['1500', '1500 TRX', '2500', '3500', 'Inny'],
        Renault: [
            '10', '11', '12', '14', '18', '19', '20', '21', '25', '30', '4', '4 E-Tech', '5', '8', '9',
            'Alaskan', 'Alpine A110', 'Alpine A310', 'Alpine V6', 'Arkana', 'Austral', 'Avantime', 'Captur',
            'Clio', 'Coupe', 'Espace', 'Express', 'Fluence', 'Fuego', 'Grand Espace', 'Grand Scenic',
            'Kadjar', 'Kangoo', 'Koleos', 'Laguna', 'Latitude', 'Master', 'Megane', 'Modus', 'Rafale',
            'Safrane', 'Scenic', 'Scenic Conquest', 'Scenic RX4', 'Symbioz', 'Talisman', 'Thalia', 'Trafic',
            'Twingo', 'Twizy', 'Vel Satis', 'Wind', 'Zoe', 'Inny',
        ],
        Rivian: ['R1S', 'R1T', 'R2', 'R3', 'Inny'],
        'Rolls-Royce': [
            'Corniche', 'Cullinan', 'Dawn', 'Flying Spur', 'Ghost', 'Park Ward', 'Phantom', 'Silver Cloud',
            'Silver Down', 'Silver Seraph', 'Silver Shadow', 'Silver Spirit', 'Silver Spur', 'Spectre',
            'Touring Limousine', 'Wraith', 'Inny',
        ],
        Rover: [
            '100', '111', '114', '115', '200', '213', '214', '216', '218', '220', '25', '400', '414', '416',
            '418', '420', '45', '600', '618', '620', '623', '75', '800', '820', '825', '827', 'City Rover',
            'Metro', 'MG', 'Mini', 'Montego', 'SD', 'Streetwise', 'Inny',
        ],
        Rox: ['01'],
        Saab: ['9-2X', '9-3', '9-3X', '9-5', '9-7X', '90', '900', '9000', '96', '99', 'Inny'],
        SARINI: ['M1', 'M1 LUQI', 'PIAWA', 'X7', 'X8', 'X9'],
        Saturn: ['Sky'],
        Seat: [
            'Alhambra', 'Altea', 'Altea XL', 'Arona', 'Arosa', 'Ateca', 'Cordoba', 'Exeo', 'Exeo ST',
            'Ibiza', 'Ibiza ST', 'Inca', 'Leon', 'Leon Sportstourer', 'Malaga', 'Marbella', 'Mii', 'Ronda',
            'Tarraco', 'Terra', 'Toledo', 'Inny',
        ],
        Seres: ['3', '5', 'SF5', 'Inny'],
        Shuanghuan: ['Sceo', 'Inny'],
        Simca: ['Matra'],
        Skoda: [
            '100', '105', '120', '130', '135', 'Citigo', 'Elroq', 'Enyaq', 'Epiq', 'Fabia', 'Favorit',
            'Felicia', 'Forman', 'Kamiq', 'Karoq', 'Kodiaq', 'Octavia', 'Peaq', 'Praktik', 'RAPID',
            'Roomster', 'Scala', 'Superb', 'Yeti', 'Inny',
        ],
        Skywell: ['ET5', 'Inny'],
        Skyworth: ['CE11', 'K', 'K-i'],
        Smart: ['#1', '#3', '#5', 'Crossblade', 'Forfour', 'Fortwo', 'Roadster', 'Roomster', 'Inny'],
        Sportequipe: ['6 GT', '7 GTW', '8 GT'],
        'SsangYong/KGM': [
            'Actyon', 'Family', 'Korando', 'Kyron', 'Musso', 'Rexton', 'Rodius', 'Tivoli', 'Tivoli Grand',
            'Torres', 'XLV', 'Inny',
        ],
        Stelato: ['S9', 'S9T'],
        Subaru: [
            '1800 Coupe', 'Ascent', 'B9 Tribeca', 'Baja', 'BRZ', 'Crosstrek', 'E-Outback', 'Forester',
            'G3X Justy', 'Impreza', 'Justy', 'Legacy', 'Leone', 'Levorg', 'Outback', 'Solterra', 'SVX',
            'Trezia', 'Tribeca', 'Uncharted', 'Vivio', 'WRX', 'XT', 'XV', 'Inny',
        ],
        Suzuki: [
            'Across', 'Alto', 'Baleno', 'Cappucino', 'Carry', 'Celerio', 'e VITARA', 'Fronx', 'Grand Vitara',
            'Ignis', 'Jimny', 'Kizashi', 'Liana', 'LJ', 'Reno', 'S-Cross', 'Samurai', 'SJ', 'Splash',
            'Super-Carry', 'Swace', 'Swift', 'SX4', 'SX4 S-Cross', 'Vitara', 'Wagon R+', 'X-90', 'XL7',
            'Inny',
        ],
        SWM: ['G01 Pro', 'G01F', 'G03F', 'G05', 'Inny'],
        Syrena: ['101', '102', '103', '104', '105', 'Bosto', 'R-20', 'Inny'],
        Tarpan: ['Inny'],
        Tata: ['Indica', 'Indigo', 'Nano', 'Safari', 'Xenon', 'Inny'],
        Tazzari: ['Zero', 'Inny'],
        Tesla: ['Cybertruck', 'Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster', 'Inny'],
        Toyota: [
            '4-Runner', 'Auris', 'Avalon', 'Avensis', 'Avensis Verso', 'Aygo', 'Aygo X', 'bZ4X', 'C-HR',
            'C-HR+', 'Camry', 'Camry Solara', 'Carina', 'Celica', 'Corolla', 'Corolla Cross',
            'Corolla Verso', 'Cressida', 'Crown', 'Dyna', 'FJ', 'Fortuner', 'GR Corolla', 'GR Yaris', 'GR86',
            'Grand Highlander', 'GT86', 'Hiace', 'Highlander', 'Hilux', 'iQ', 'Land Cruiser', 'Lite-Ace',
            'Matrix', 'Mirai', 'MR2', 'Paseo', 'Picnic', 'Previa', 'Prius', 'Prius+', 'ProAce',
            'Proace City', 'Proace City Verso', 'Proace Verso', 'RAV4', 'Sequoia', 'Sienna', 'Starlet',
            'Supra', 'Tacoma', 'Tercel', 'Tundra', 'Urban Cruiser', 'Venza', 'Verso', 'Verso S', 'Yaris',
            'Yaris Cross', 'Yaris Verso', 'Inny',
        ],
        Trabant: ['601', 'P 50', 'Inny'],
        Triumph: ['Dolomite', 'Moss', 'Spitfire', 'TR3', 'TR4', 'TR5', 'TR6', 'TR7', 'TR8', 'Inny'],
        TUATARA: ['1000 EFI', '1500 Electric'],
        Uaz: ['3153', '3162', '452', '469 B', 'Inny'],
        Vanderhall: ['Venice'],
        Vauxhall: ['Astra', 'Frontera', 'Omega', 'Vectra', 'Vivaro', 'Inny'],
        VELEX: ['Inny'],
        Volkswagen: [
            '181', 'Amarok', 'Arteon', 'Arteon Shooting Brake', 'Atlas', 'Beetle', 'Bora', 'Buggy', 'Caddy',
            'California', 'Caravelle', 'CC', 'Corrado', 'Crafter', 'Eos', 'Fox', 'Garbus', 'Golf',
            'Golf Alltrack', 'Golf Cabrio', 'Golf Plus', 'Golf Sportsvan', 'Golf Variant', 'ID. Buzz',
            'ID. Polo', 'ID. Unyx 06', 'ID.3', 'ID.3 Neo', 'ID.4', 'ID.5', 'ID.6', 'ID.7', 'ID.7 Tourer',
            'Iltis', 'Jetta', 'Kafer', 'Karmann Ghia', 'LT', 'Lupo', 'Multivan', 'New Beetle', 'Passat',
            'Passat Alltrack', 'Passat CC', 'Passat Variant', 'Phaeton', 'Polo', 'Polo Cross', 'Routan',
            'Santana', 'Scirocco', 'Sharan', 'T-Cross', 'T-Roc', 'Taigo', 'Tayron', 'Teramont', 'Tiguan',
            'Tiguan Allspace', 'Touareg', 'Touran', 'Transporter', 'up!', 'Vento', 'Inny',
        ],
        Volvo: [
            '245', '262', '340', '744', '745', '780', '850', '855', '945', '965', 'C30', 'C40', 'C70',
            'EC40', 'EM90', 'ES90', 'EX30', 'EX60', 'EX90', 'MY23', 'P1800', 'Polar', 'S40', 'S60',
            'S60 Cross Country', 'S70', 'S80', 'S90', 'Seria 200', 'Seria 300', 'Seria 400', 'Seria 700',
            'Seria 900', 'V40', 'V40 Cross Country', 'V50', 'V60', 'V60 Cross Country', 'V70', 'V90',
            'V90 Cross Country', 'XC 40', 'XC 60', 'XC 70', 'XC 90', 'Inny',
        ],
        Voyah: ['Dream', 'Free', 'Taishan'],
        Warszawa: ['203', '204', '223', '224', 'M-20', 'Pick-up', 'Inny'],
        Wartburg: ['1.3', '311', '312', '313', '353', 'Inny'],
        Wey: ['Alpine', 'Gaoshan', 'Lanshan', 'Latte', 'Mocha', 'Inny'],
        'Wołga': ['2410', 'GAZ-21', 'GAZ-24', 'Inny'],
        Xiaomi: ['SU7', 'YU7', 'Inny'],
        XPeng: ['G3i', 'G6', 'G9', 'GX', 'P5', 'P7', 'P7+', 'X9'],
        'Zaporożec': ['965', '968', 'Inny'],
        Zastava: ['1100', '750', 'Inny'],
        ZEEKR: ['001', '007', '009', '7X', '8X', '9X', 'X', 'Inny'],
        Zefir: ['Inny'],
        Zhidou: ['D1', 'D2', 'D3', 'KWB', 'Inny'],
        'Żuk': ['Inny'],
    },
    MOTORCYCLE: {
        '79Bike': ['Falcon GT', 'Falcon Pro'],
        Access: ['DRR', 'Max', 'Tomahawk', 'Warrior', 'Inny'],
        Adly: [
            'Air Tec', 'AT', 'Cat', 'Fun Cruiser', 'Jet', 'Noble', 'Panther', 'Road Tracer', 'Rooster',
            'Silver Fox', 'Super Sonic', 'TB', 'Thunder Bike', 'Inny',
        ],
        Aeon: [
            'Aero', 'Argon', 'Cobra', 'Crossland', 'Cube', 'Echo', 'Goes', 'LG', 'Mini Kolt', 'Newark',
            'Nox', 'Overland', 'Pulsar', 'Regal', 'Revo', 'SP', 'Stinger', 'Super Sport', 'Utility', 'Inny',
        ],
        AGM: ['Retro 50'],
        AJP: ['Galp', 'PR4', 'Inny'],
        AJS: ['M16', 'Spring Twin', 'Stormer', 'Inny'],
        Alfarad: ['Explorer 350S', 'Inny'],
        'Altis Powersports': ['Delta', 'Sigma'],
        Amperi: ['Amore', 'D2D Donk', 'Newbot Storm', 'Pulse', 'Range', 'Tiger'],
        APOLLO: ['RFZ', 'RXF', 'Inny'],
        Aprilia: [
            'AF1', 'Amico', 'Area', 'Arrecife', 'Atlantic', 'Caponord', 'Classic', 'Climber', 'Dorsoduro',
            'ETV', 'ETX', 'Falco', 'Gulliver', 'Habana', 'Leonardo', 'Mana', 'Mini RX', 'Mojito', 'Moto',
            'MX', 'MXV', 'Pegaso', 'Rally', 'RC', 'Red Rose', 'RS', 'RST', 'RSV', 'RSW', 'RX', 'RXV',
            'Scarabeo', 'Shiver', 'SL', 'SMV', 'Sonic', 'Sportcity', 'SR', 'SRV 850', 'Stealth', 'SX', 'SXR',
            'SXV', 'Tuareg', 'Tuono', 'Inny',
        ],
        'Arctic Cat': ['400', '500', '650', 'Inny'],
        Ariic: ['318', 'Brio 2', 'Gemma', 'Gobi', 'Julio 2', 'Touch'],
        ASIX: [
            '706', '710', 'Challanger 300', 'Commander', 'Cyber', 'Cyber 250', 'Cyber 250-T3B', 'E-M10',
            'E-M11', 'Fourcraft 125', 'Fourcraft 250 Ultra', 'Gladiator', 'Hunter', 'Lizzard', 'M10',
            'Magnum 200', 'Muddy', 'Ranger', 'Tytan 200RR', 'XB', 'XB-28', 'XB-83', 'XB-88', 'XB-88 250cc',
            'XB-88 300cc', 'XR', 'XR-99', 'XT', 'XT-97', 'Inny',
        ],
        Askoll: ['eS1', 'eS2', 'eS3', 'eSpro45', 'eSpro70', 'NGS1', 'NGS2', 'NGS3', 'Inny'],
        Bajaj: [
            'Avenger', 'BYK', 'Caliber', 'Chetak', 'Classic', 'CT', 'Discover', 'Dominar 400', 'Eliminator',
            'KB', 'Kristal', 'Platina', 'Pulsar', 'Qute', 'RTZ', 'Spirit', 'Super', 'SX Enduro', 'Wave',
            'Wind', 'XCD', 'Inny',
        ],
        Baotian: ['BT49QT', 'Citibike', 'Eagle', 'Evolution', 'Falcon', 'Monza', 'Tanco', 'Inny'],
        Barton: [
            'Active', 'B-Max', 'B-Max 125', 'BLADE-R', 'Braver 300', 'BXF 150 PRO', 'Cafe Racer', 'Classic',
            'Coral', 'Coral 125', 'Coral 50', 'Cross', 'DB125-3L', 'Dirtman', 'DISCOVER 200', 'Duel X 125',
            'E-Max One', 'Energy', 'eVivo', 'Falcon', 'Fighter', 'Flash', 'FR', 'FRX 125', 'GT', 'Hyper',
            'MZK', 'Naked', 'NOXO 125', 'NXT', 'NXT 125', 'NXT 150', 'NXT 250', 'NXT 300', 'Pentora',
            'QUAD EXPLORER', 'Quatro', 'Rally 125', 'Rally 125 DUO', 'Ranger Classic', 'Raptor', 'Raze',
            'Rocky', 'Scalpel', 'Sprint', 'Stratos', 'Street-R', 'T-rex', 'Thor', 'Traverse 125', 'Tres',
            'Volcano', 'Volt', 'Warrior', 'X-Trail', 'Yadea', 'Z', 'Inny',
        ],
        Bashan: [
            'BS110s-7', 'BS125s-2', 'BS150-2', 'BS150s-3g', 'BS150s-3h', 'BS200s-6a', 'BS200s-7',
            'BS250s-11b', 'BS250s-24', 'BS250s-30', 'BS250s-5', 'BS250s-9', 'BS300s-18a', 'BS300s-a',
            'BS400s', 'BS50s-7', 'Inny',
        ],
        BearEbike: ['Russell Desert', 'Russell Military', 'Russell Nitro', 'Russell Ultimate'],
        Benda: [
            'Chinchilla 125', 'Chinchilla 300', 'Chinchilla 450', 'Chinchilla 500', 'Dark Flag 500',
            'FLC 700', 'LFC 700', 'Napoleon 125', 'Napoleon 250', 'Napoleon 500', 'Redstone 1000',
            'Redstone 550', 'Rock 125', 'Street 125', 'Inny',
        ],
        Benelli: [
            '302 S', '502 C', '752 S', 'Banshee', 'BKX', 'BKX 125S', 'BN 125', 'BN 251', 'BN 302', 'Buzzer',
            'BX', 'Devil', 'Fireball', 'IMPERIALE 400', 'Jarno', 'K2', 'Leoncino', 'Leoncino Trail', 'LS',
            'Mojave', 'Pepe', 'Quattro Nove', 'SEI', 'Sport', 'TNT', 'Tornado', 'Tornado Naked T', 'TRE',
            'TRE-K', 'TRK 125', 'TRK 251', 'TRK 502', 'TRK 502X', 'TRK 702', 'TRK 702X', 'TRK 902 Stradale',
            'TRK 902 Xplorer', 'Velvet', 'Inny',
        ],
        Benyco: ['Inny'],
        Benzer: ['Colorado', 'Dakota', 'Daytona', 'Florida', 'Indiana', 'Ohio', 'Texas', 'Inny'],
        Berreta: [
            'Abt 125', 'Abt 150', 'Abt 250', 'Abt 300', 'Abt 909r', 'Bulldog', 'Eco 1000 W', 'Egl 110',
            'Egl 125', 'Egl 150', 'Egl Mad Max', 'Egl Th200', 'Flipper 50', 'Hummer 200', 'Kids', 'Kids Eco',
            'Mikilon 125', 'Mikilon Hummer 200', 'Scream', 'Sport', 'Sport Eco', 'Turbo', 'Varia', 'Inny',
        ],
        Beta: [
            'Alp', 'Ark', 'ART', 'Eikon', 'Euro', 'Evo', 'Jonathan', 'KR', 'M4', 'Minicross', 'Minitrial',
            'Motard', 'Quadra', 'REV', 'RR', 'Synt', 'Techno', 'TR', 'TX', 'Zero', 'Inny',
        ],
        'Big Bear Choppers': ['Athena'],
        'Big Dog': ['K-9', 'Mastiff', 'Pitbull', 'Ridgeback', 'Inny'],
        'Bili Bike': [
            '500', 'Anger', 'Chopper', 'CITY GO', 'Dynamic', 'E-Baldur', 'E-Baldur Delivery', 'Ecomo',
            'Extreme', 'Future', 'Grace', 'Harley', 'Hawk', 'Hawk Delivery', 'J1', 'J2', 'Leon', 'Miku Max',
            'Next', 'Robo-S', 'Ronic', 'S-Way', 'S-Way Max', 'S3', 'S4', 'S5', 'S5 Delivery', 'Shino',
            'Sigma', 'Super Miku', 'X1', 'Inny',
        ],
        'Bili Coco': [
            'Big Chopper', 'Chopper', 'Cobra', 'Cobra Trójkołowa', 'Coco', 'Coco Baltic', 'Coco Strong',
            'Dynamic', 'Future', 'G4', 'G5', 'G6', 'G7', 'G8', 'G9', 'Grand', 'Strong', 'Trójkołowy',
            'Trójkołowy Sport', 'Inny',
        ],
        Bimota: ['BX450', 'KB4', 'KB4 RC', 'KB998 Rimini', 'TERA', 'TESI H2'],
        Blinc: ['Alfa', 'Beta', 'Falcon', 'Fantasy'],
        BMW: [
            'Adventure', 'C 400 GT', 'C 400 X', 'C 650 sport', 'C1', 'C600 Sport', 'C650 GT', 'CE 02',
            'CE 04', 'CS', 'F', 'G', 'GS', 'K', 'LT', 'M4', 'R', 'R1250 GS Adventure', 'RS', 'RT', 'S', 'XR',
            'Inny',
        ],
        BNP: ['Avant', 'Booster', 'Monster', 'Pixel', 'Zevs', 'Inny'],
        Bombardier: ['Outlander', 'Quest', 'Rally', 'Sarasota', 'Spyder', 'Traxter', 'Inny'],
        BOOM: ['Family', 'Fighter', 'Highway', 'Low Rider', 'Mustang', 'Mustang Family', 'Mustang ST1'],
        'Boss Hoss': ['Inny'],
        'BPG Werks': ['DTV Shredder'],
        BRCP: ['GRIT 1000R'],
        Brixton: ['Cromwell', 'Crossfire', 'Felsberg', 'Rayburn', 'Sunray', 'Inny'],
        BSA: [
            'B', 'Bantam', 'Bantam 350', 'C', 'Gold Star', 'Gold Star 650', 'Goldflash', 'GP Victor',
            'Lightning', 'M', 'Scrambler 650', 'Super Rocket', 'Twin Shooting Star', 'Victor',
            'Victor Super Sport', 'XB', 'Inny',
        ],
        Buell: ['Blast', 'CityX Lightning', 'M', 'S', 'S3', 'X', 'XB', 'Inny'],
        Cagiva: [
            'Alazzurra', 'Aletta', 'Blues', 'Canyon', 'City', 'Cocis', 'Cruiser', 'Elefant', 'Freccia', 'GP',
            'Mito', 'Navigator', 'Planet', 'Prima', 'Raptor', 'River', 'Roadster', 'S2', 'SST', 'Stella',
            'Super City', 'SXT', 'T4', 'Tamanaco', 'W', 'Inny',
        ],
        CAKE: ['Bukk', 'Kalk', 'Makka', 'Ösa'],
        'Can-Am': [
            'DS', 'Maverick', 'Outlander', 'Outlander Max', 'Renegade', 'Ryker', 'Spyder', 'Youth', 'Inny',
        ],
        CCM: ['GP450 Adventure', 'Inny'],
        CECTEK: ['Estoc', 'Gladiator', 'Kingcobra', 'Quadrift'],
        CFMoto: [
            '1000 MT-X', '300NK', '450CL-C', '450CL-C Bobber', '450L', '450MT', '450NK', '450SR', '650 MT',
            '675NK', '675SR', '700CL-X Adventure', '700CL-X Heritage', '700MT', '800MT Explore',
            '800MT Sport', '800MT Touring', '800MT-X', '800NK', 'Allroad', 'CForce', 'CL-C', 'CL-X', 'CX-2E',
            'CX-5E', 'MT', 'MT-X', 'NK', 'SR', 'UForce', 'ZForce', 'Inny',
        ],
        'City-bike': ['1', '2', 'MaxiSport', 'Moped', 'Retro', 'Sport', 'Inny'],
        'Cobra Moto': ['CX 50 BW', 'CX 50 jr.', 'CX 50 SW', 'CX 65'],
        CORVUS: ['Inny'],
        COSMOPOLITAN: ['Inny'],
        CPI: [
            'Aragon', 'Bingo', 'GTR', 'GTS', 'Hussar', 'Oliver', 'Popcorn', 'Show FB', 'SM', 'SX', 'X-Large',
            'XS', 'Inny',
        ],
        'CR&S': ['DUU', 'VUN'],
        'Cross IMR': ['FX', 'FXR', 'LX', 'MX', 'SX', 'TT', 'Inny'],
        CZ: [
            '125', '125 Cross', '175', '175 Enduro', '180', '250', '250 Cross', '350', '380', '400', '500',
            'Inny',
        ],
        Daelim: [
            'Altino', 'History', 'Liberty', 'Message', 'NS', 'Roadwin', 'S-Five', 'S2', 'S3', 'Tapo', 'VL',
            'VS', 'VT', 'Inny',
        ],
        Daytona: [
            'Dymoto 125', 'Dymoto 125 X', 'Mista 125', 'Orama 125', 'Rockstar 125', 'Rockstar 450V', 'Inny',
        ],
        Derbi: [
            'Antorcha', 'Atlantis', 'Boulevard', 'FDS', 'Fenix', 'GP1', 'GPR', 'GPR Nude', 'Hunter',
            'Manhattan', 'Paddock', 'Predator', 'Senda', 'TT8', 'Vamos G', 'Variant', 'X-Treme', 'Inny',
        ],
        Diabolini: ['Buggy', 'Cobra', 'Diablo 200', 'Diablo HOM', 'FX 150cc', 'X8 250 CC', 'Inny'],
        Dinli: ['Beast', 'Centhor', 'Cobia', 'Diablo', 'Diamond Back', 'Dino', 'DL603', 'JP', 'Inny'],
        DKW: ['Ks 200', 'Nz', 'RT 3', 'Sb 500', 'Inny'],
        Dniepr: ['K 650', 'K 750', 'M-72', 'MT-10', 'MT-11', 'MT-12', 'MT-16', 'MT-9', 'Inny'],
        Doohan: ['iLark', 'iTango', 'iTank', 'Inny'],
        Ducati: [
            '1098', '1198', '1199 Panigale', '160', '200 GT', '250', '350 SS', '400 F3', '450', '500',
            '600 SS', '620', '696', '748', '749', '750', '848', '851', '860', '888', '900', '906', '907',
            '916', '955', '959 Panigale', '996', '998', '999', 'Bris 48-1', 'DesertX', 'Desmo',
            'Desmosedici', 'Diavel', 'Ds 1000', 'F1', 'Hypermotard', 'Mach 1', 'Mark 3', 'MH 900',
            'MHR 1000', 'Monster', 'Multistrada', 'Panigale 1299', 'Panigale 899', 'Panigale V2',
            'Panigale V4', 'Panigale V4R', 'Panigale V4S', 'Pantah', 'Paso 750', 'Paso 907', 'Radical',
            'Scrambler', 'Sport Classic', 'SS 1000', 'SS 800', 'ST2', 'ST3', 'ST4', 'Streetfighter 1098',
            'Streetfighter 848', 'Streetfighter V2', 'Streetfighter V4', 'SuperSport', 'Inny',
        ],
        'E Ride Pro': ['S', 'SS', 'SS 3.0'],
        'E-mio': ['Agile', 'Destina', 'Toro', 'Vento'],
        'Eagle Motorsports': ['ATV 200', 'ATV 250', 'Lyda 203C', 'Lyda 203E', 'Inny'],
        eFun: ['Lipo45', 'Lipo70', 'Pusa45', 'Pusa90', 'Tiger100', 'Inny'],
        'EGL Eglmotor': ['EXP', 'KEX AIR', 'Lyda', 'Lyrx', 'Madix'],
        ELECTRORIDE: [
            'FASTER', 'FASTER MAX', 'FASTI 3', 'FASTI 4', 'FROST', 'Futuri 3', 'Futuri 4', 'PIXI', 'TRIKE',
            'TRIO', 'Inny',
        ],
        'Elon Motors': ['Elon One 50 Km', 'Elon One 80 Km'],
        Energica: ['EVA', 'EVA EsseEsse9', 'Inny'],
        Enormis: [
            'Arcum', 'Cargo 150', 'Cargo ZS', 'Doudi', 'iDo', 'iDou', 'Pass 120', 'Pass P1', 'Sprint',
            'Uranus', 'Vigo',
        ],
        Evoyager: ['BN022', 'BN027', 'BN712', 'LMI YM2000'],
        Fantic: ['Cabalero 125', 'Cabalerro 50', 'TX', 'Inny'],
        Faspider: ['Arana Club', 'F8', 'Roma', 'Scootworks', 'Inny'],
        'FD MOTORS': ['F3', 'F5'],
        FECHT: ['Inny'],
        Ferro: [
            '101', '121', '123', '301', '302', '303', '601', '602', '603', '604', '605', '606-2', '802',
            '803', '901', 'Inny',
        ],
        'FK Motors': ['FK-12MS', 'FK-12SF', 'FK-12SX', 'FK-12TA'],
        FYM: ['FY 250', 'Scooter', 'Inny'],
        Garelli: ['Inny'],
        'Gas Gas': [
            'Delta', 'EC', 'Halley', 'JT', 'JTR', 'MC', 'Pampera', 'SM', 'Trial', 'TXT', 'XC', 'Inny',
        ],
        Gateway: ['R5', 'R6', 'Rider II', 'Spider', 'Inny'],
        'GB Motors': [
            'Beast', 'Blade', 'Cruiser', 'Cyclone', 'First', 'Neox', 'Pinacolada', 'Razor X', 'Rocket',
            'Spark', 'Street', 'Thunder', 'Tiger Max', 'Toxic', 'Virus', 'Inny',
        ],
        Geely: ['Alta', 'Inny'],
        Generic: ['Cracker', 'Ideo', 'Tiger', 'XOR', 'Inny'],
        Gilera: [
            '125 R', '503', 'Apache 125', 'Cougar', 'Crono', 'CX 125', 'Dakota 125', 'DNA', 'Eaglet 50',
            'GFR 125', 'GPR', 'GSM', 'GTA 125', 'Ice 50', 'KK', 'KZ', 'MXR', 'Nexus 500', 'Nordwest', 'R 1',
            'RC', 'RCR', 'RK', 'Runner', 'RX', 'Saturno 500', 'Sioux', 'Smash 110', 'SMT', 'SP',
            'Stalker 50', 'Typhoon 50', 'XR1', 'XR2', 'YL 150', 'Zulu 50', 'Inny',
        ],
        Goes: ['COBALT MAX', 'COPPER 3.0', 'IRON MAX', 'Terrox', 'Inny'],
        Greenwolke: ['1.0SL', '2.0SL', '5.1SL', '6.1SL'],
        Hanway: ['B15', 'B40', 'B50', 'Bob400', 'NK125s', 'NK300', 'YP500', 'Inny'],
        'Harley-Davidson': [
            'Bad Boy', 'Cafe Racer', 'Custom Low Rider', 'CVO Street Glide', 'Dyna', 'Dyna Fat Bob',
            'Dyna Glide', 'Dyna Low Rider', 'Dyna Street Bob', 'Dyna Super Glide', 'Dyna Switchback',
            'Dyna Wide Glide', 'Electra', 'Evolution Sportster', 'FL Duo Glide', 'FL Hydra Glide',
            'FLH Electra Glide', 'FLH Shovelhead', 'FLHS Electra Glide', 'FLHT Electra Glide Standard',
            'FLHTCU Ultra', 'FLHXS Special', 'FXSB Breakout', 'LiveWire', 'Night Train', 'Pan America',
            'Softail', 'Softail Blackline', 'Softail Breakout', 'Softail Cross Bones', 'Softail Custom',
            'Softail Deluxe', 'Softail Fat Bob', 'Softail Fat Boy', 'Softail FXDR',
            'Softail Heritage Classic', 'Softail Low Rider', 'Softail Slim', 'Softail Sport Glide',
            'Softail Springer Classic', 'Softail Standard', 'Softail Street Bob', 'Softail V-Rod',
            'Sportster', 'Sportster Custom 1200C', 'Sportster Custom 883C', 'Sportster Forty-Eight',
            'Sportster Iron 1200', 'Sportster Iron 883', 'Sportster Low 883L', 'Sportster Nightster 1200N',
            'Sportster Nightster 975', 'Sportster Roadster 1200R', 'Sportster Roadster 883R',
            'Sportster Seventy-Two', 'Sportster Superlow', 'Street 750', 'Street Glide Trike',
            'Street Rod XG 750A', 'Street XG 750', 'Super Glide', 'Touring Electra Glide',
            'Touring Road Glide', 'Touring Road King', 'Touring Street Glide', 'Touring Ultra Limited',
            'Tri Glide', 'Trike Freewheeler', 'V-Rod Muscle', 'V-Rod Night Rod', 'V-Rod Street Rod', 'WL',
            'WR', 'XR 1200', 'Inny',
        ],
        Hartford: ['HD', 'VR', 'Inny'],
        Hercules: ['K 125', 'K 50', 'MC', 'Prima', 'Supra 4 Enduro', 'Supra 4 GP', 'W 2000', 'Inny'],
        Hero: ['Puch Winner', 'Inny'],
        HISUN: [
            'Forester', 'Freelander', 'Guardian 400', 'Guardian 550', 'Guardian 750', 'Tactic 250',
            'Tactic 550', 'Inny',
        ],
        HM: ['CRE', 'Inny'],
        Honda: [
            'Activa', 'ADV350', 'Amigo', 'ANF', 'AX', 'Bali', 'Biz', 'C', 'CA', 'CB', 'CBF', 'CBR', 'CBX',
            'CBZ', 'CD', 'CDI', 'CF', 'CG', 'CGL', 'CHF', 'CL', 'CLR', 'CM', 'CMX', 'CN', 'CR', 'CRF', 'CRM',
            'CS', 'CT', 'CTX', 'CX', 'Deauville', 'Dio', 'DJ1', 'DN-01', 'Dylan', 'EC', 'Elite', 'EM1', 'EX',
            'Express', 'FES', 'FJS', 'FMX', 'FourTrax', 'FSC', 'FSX', 'FT', 'FX', 'GB', 'GL', 'GLX',
            'Gorilla', 'Gyro', 'Hornet', 'Lead', 'LJ', 'LS', 'MB', 'MBX', 'Montesa Repsol', 'MR', 'MSX 125',
            'MSX125', 'MT', 'MTX', 'MVX', 'NB', 'NC', 'ND', 'Nighthawk', 'Nova', 'NPS', 'NQ', 'NR', 'NS',
            'NSR', 'NSS', 'NT', 'NTV', 'NV', 'NX', 'NXR', 'Pantheon', 'PC', 'PCX', 'PES', 'PXR', 'QA', 'QR',
            'Rancher', 'RC', 'Reflex', 'Rincon', 'RS', 'RVF', 'S-Wing', 'SCF', 'Scrambler', 'SFX', 'SH',
            'Shadow', 'Silver Wing', 'SL', 'ST', 'Super Cub', 'SW-T400', 'TA', 'TL', 'TLR', 'TMX',
            'Transalp', 'TRX', 'Valkyrie', 'Varadero', 'VF', 'VFR', 'Vision', 'VT', 'VTR', 'VTX', 'VTZ',
            'Wallaroo', 'Wave 110i', 'WN7', 'X-ADV', 'X11', 'X4', 'X8R', 'XBR', 'XL', 'XLR', 'XLV', 'XR',
            'XRM', 'XRV', 'Z', 'ZB', 'Zoomer', 'ZR', 'Inny',
        ],
        Horwin: ['CR6', 'EK1', 'EK3', 'Monkey', 'SK1', 'SK3', 'Inny'],
        Hummer: ['altul', 'Inny'],
        Husaberg: ['FC', 'FE', 'FS', 'Inny'],
        Husqvarna: [
            '250', '390 CR', '401', '430 XC', '510 Cross Country', '701', 'CR', 'FC', 'FE', 'FM', 'FS', 'FX',
            'Husky Boy', 'Norden', 'NOX', 'Nuda 900R', 'SM', 'Svartpilen', 'TC', 'TE', 'TX', 'Vitpilen',
            'WR', 'WRE', 'WSE', 'WXE', 'Inny',
        ],
        Hyosung: ['Cruise II', 'GT', 'GT Comet', 'GV', 'Rush', 'RX', 'SF 50', 'Super Cab 50', 'XRX', 'Inny'],
        iamelectric: [
            'ARIEL', 'Blade M', 'Blade S', 'Dream 2', 'Eagle', 'Grace', 'Grace Double', 'Havana',
            'Havana Double', 'Hawk Double', 'Horwin CR6', 'Horwin EK3', 'Horwin Ranger', 'iTank', 'Lala',
            'Life', 'LIFE4', 'Miku Max', 'MV Racer', 'NCE-S', 'NEMO', 'On Time', 'PCX-E', 'Robo-S',
            'Robo-SC', 'Roma GT', 'S3', 'S3 Double', 'S4', 'S5', 'S5 Delivery', 'S5 Double', 'Swift',
            'T-REX', 'TS-MAX', 'X1 Double', 'Yadea C1S', 'Inny',
        ],
        IFA: ['BK 350', 'RT 125', 'Inny'],
        Indian: [
            '741', 'Challenger', 'Chief', 'Chieftain', 'FTR', 'Roadmaster', 'Scout', 'Springfield',
            'Vintage', 'Inny',
        ],
        Italjet: [
            'Baby 50', 'Dragster', 'Formula', 'JC', 'Milennium', 'MX', 'PR', 'Torpedo', 'Velocifero', 'Inny',
        ],
        'IŻ': ['Inny'],
        Jawa: [
            '125', '175', '175 typ 356', '250', '250 typ 353', '300 CL', '350', '350 42 Bobber', '350 CL',
            '350 CL Perak', '350 OHC', '350 OHC Sport', '42 CL LE', '50', '500', '500 RVM ADV',
            '500 RVM SCR', '634 Retro 2T', '640 News Style 2T', '650 OHC', '650 OHC Sport', '750 Racing',
            '750 Retro', '750 Touring', '750 Touring GT', '895', 'Babetta', 'Dandy', 'Enduro Sport', 'FJ 42',
            'GEENY 400', 'Mustang 50', 'Robby', 'Stella', 'TS 350', 'Inny',
        ],
        JHL: ['LX300', 'MX250', 'MX300'],
        Jincheng: ['JC 125-17B', 'JC 50', 'Knight', 'Wild Cat', 'Inny'],
        JML: ['EN250i', 'EN250i PRO', 'EN300'],
        Journeyman: ['Gladiator', 'Stormer', 'Inny'],
        JTG: ['Enduro', 'Trial'],
        Junak: [
            '103', '104', '106', '108', '109', '121', '125', '125 Racer', '125S', '607', '711', '712', '805',
            '806', '901', '901 RS', '902', '904', '905', '906', '907', 'ADV', 'B20', 'Classico 125',
            'Classico 50', 'Furious', 'M', 'M11', 'M12', 'M14', 'M15', 'M16', 'M18', 'RAW 125', 'RAW 50',
            'RSL 125', 'RX One', 'RX-401', 'RX600', 'SC Furious', 'SR', 'Vintage', 'X-Ray', 'Inny',
        ],
        Kandi: ['Cowboy e10K', 'Innovator e10K', 'Lucky T9'],
        Kawasaki: [
            '1000 GTR', 'BN', 'Brute Force', 'Concours', 'EL', 'Eliminator 500', 'EN', 'ER', 'Estrella', 'F',
            'FX', 'GPX', 'GPZ', 'GT', 'GTR', 'H1', 'H2', 'Kazer', 'KFX', 'KLE', 'KLR', 'KLV', 'KLX', 'KX',
            'KZ', 'LTD', 'Ninja', 'Ninja 1000 SX', 'Ninja 250R', 'Ninja 300 ABS', 'Ninja 400', 'Ninja 500',
            'Ninja H2 SX', 'Spectre', 'Versys 1000', 'Versys 1100', 'Versys 1100 S', 'Versys 1100 SE',
            'Versys 650', 'Versys-X 300', 'VN', 'Vulcan', 'Vulcan S', 'Z', 'Z 1000', 'Z 125', 'Z 500',
            'Z 500 SE', 'Z 650', 'Z 650 RS', 'Z 900', 'Z 900 RS', 'Zephyr', 'ZL', 'ZR', 'ZRX', 'ZX', 'ZXR',
            'ZZR', 'Inny',
        ],
        KAYO: ['125 TT', 'AU', 'K2', 'K2 PRO', 'K5', 'KT250', 'T4', 'Inny'],
        Keeway: [
            'Arn', 'ATV', 'ATV Dragon', 'Cruiser', 'F-act-Fact-NKD', 'Flash', 'Focus', 'Goccia', 'Hacker',
            'Hurricane', 'K-Light 125', 'Matrix', 'Mini ATV', 'Outlook', 'Pixel', 'RKF', 'RKS 125', 'Ry-8',
            'Speed', 'Superlight', 'Supershadow', 'Swan', 'TX', 'Venus', 'Versilia', 'Vieste', 'Viva',
            'X-Light 125', 'X-ray', 'Inny',
        ],
        Kentoya: ['Inny'],
        Kespor: ['altul', 'SL50QT-8', 'TS50QT-4', 'TS50QT-8', 'XTR 50'],
        Kingway: [
            '150', '250MR', '500', '70', 'Alien', 'Alpinus', 'Apollo', 'Arrow', 'ATV 70', 'Barracuda',
            'Black Horse', 'Camaro', 'CAT', 'Cereno', 'Challenger', 'Chinaboy', 'Cobra', 'Coliber',
            'Commander', 'Condor', 'Corvette', 'Cross', 'CUB', 'Dinli', 'Dominator', 'El Passo', 'Euroboy',
            'Eurostar', 'Falcon', 'Fennari', 'Fonero', 'Forever', 'FOX', 'Gallus', 'Guliver', 'Hassan',
            'Hooligan', 'Hummer', 'Ibis', 'Jinlun', 'Johnatan', 'Jonathon', 'Jumper', 'King', 'Koyot',
            'Lander', 'Linhai', 'Martinelli', 'Mini', 'Monster', 'Mosquito', 'Naked', 'Navigator', 'Paulo',
            'Poster', 'Purga', 'Quattro', 'Qurier', 'Rocky', 'Shark', 'Spider', 'Sport', 'Street', 'Swift',
            'Tanco', 'Terminator', 'Tiggero', 'Tommy', 'Touran', 'Traper', 'UFO', 'Varadero', 'Yarox',
            'Yuxin', 'Zibo', 'Inny',
        ],
        Kinroad: ['Hunter', 'Sahara', 'Wind Hunter', 'XT', 'Łoś', 'Inny'],
        Komar: ['50', 'Inny'],
        KOVE: [
            '250R', '250RR', '350RR', '450 Rally', '500F Neo Scrambler', '500F Wild', '500X ADV', '510F',
            '510X', '625X', '800X ADV', '800X Pro', '800X Rally', '800X Touring', 'MX250', 'NK125R',
            'NK321R', 'NK321RR', 'NK450RR',
        ],
        'KSR Moto': [
            'Classic 125', 'Classic 50', 'Demonio 125', 'Demonio 50', 'GRS 125', 'Pandora 50', 'Sirion 125',
            'Sirion 50', 'TR 50', 'TTX', 'TW 125', 'Vionis',
        ],
        KTM: [
            'Adventure', 'Adventure 390', 'Adventure 790', 'Adventure 890', 'Duke', 'Duke 125', 'Duke 390',
            'Duke 790', 'DUKE 890', 'Duke 990', 'Enduro', 'Enduro 125', 'Enduro 390', 'Enduro 690', 'EXC',
            'EXC 150', 'EXC 250', 'EXC 300', 'EXC 350', 'EXC 450', 'EXC 500', 'Foxi GT', 'Freeride', 'GO',
            'LC', 'LC 8', 'RC 125', 'RC 200', 'RC 250', 'RC 390', 'RC 8', 'RC 990', 'SMC', 'SMC 125',
            'SMC 390', 'SMC 690', 'SMT', 'SMT 890', 'Super Adventure', 'Super Adventure 1350',
            'Super Adventure 1390', 'Super Duke', 'Super Duke 1350', 'SX', 'SXF', 'Inny',
        ],
        KXD: ['Inny'],
        Kymco: [
            'Activ', 'Agility', 'Agility City A-C', 'AK 550', 'AK 575', 'Bet & Win', 'Calypso', 'Caro',
            'Cherry', 'City', 'CK', 'Cobra Cross', 'Cobra Racer', 'Cruiser', 'CV3', 'Dink', 'Dink-Yager',
            'DJ', 'Downtown', 'DT X125', 'DT X360', 'Ego', 'Espresso', 'Fever', 'Filly', 'Grand Dink',
            'Grand King', 'Hipster', 'KTR-KCR', 'KXR', 'Like', 'Maxxer', 'Miler', 'Mongoose KXR', 'Movie XL',
            'MXer', 'MXU', 'MyRoad', 'New Dink', 'Nexxon', 'People', 'Pulsar Luxe', 'Pulsar-CK',
            'Quannon-KR Sport', 'Skytown', 'Sooner', 'Spike', 'Stryker', 'Super', 'Super 8', 'Super 9 A-C',
            'Super 9 L-C', 'Top Boy', 'UXV', 'Venox', 'Vitality', 'Vivio', 'X-Town', 'Xciting', 'Yager GT',
            'Yup', 'Zing', 'ZX', 'Inny',
        ],
        'La Souris': ['Sourini 50', 'VX 50'],
        Lambretta: ['D', 'LI', 'SX', 'TV', 'Inny'],
        Laverda: ['3CE', '3CL', '650', '668', '750', 'Atlas', 'Jota', 'LAV', 'LZ', 'SF1', 'SFC', 'Inny'],
        Lifan: ['European', 'Hawk', 'Kahuna', 'LF', 'LH300', 'Retro', 'Rocket', 'SG', 'V-Twin', 'Inny'],
        Linhai: [
            '260', '300', '370 Promax', '420 Promax', 'ATV', 'Buck 125', 'Goon', 'Jobber',
            'Landforce 1000L EPS', 'Landforce 550L', 'Landforce 650L EPS', 'Landforce 650L PRO EPS',
            'Landforce550L EPS', 'LH-80DU Electric', 'M 210 EFi 2x4', 'Mainstreet', 'Monarch', 'Muddy',
            'Prince', 'Scooter', 'T-BOSS 650 EPS', 'Tornado', 'UTV 1100 Diesel T1b', 'UTV 670 T-BOSS EPS',
            'Inny',
        ],
        LIYA: ['Inny'],
        LML: ['50', 'LML 151 - 4T', 'Star 125- 2T', 'Star 150- 2T', 'Star 200 -4T'],
        Loncin: ['Tracker', 'XWOLF 1000', 'XWOLF 200', 'XWOLF 300', 'XWOLF 550', 'XWOLF 700', 'Inny'],
        Lotus: ['c-01'],
        'Lucky Star': ['BR', 'SP'],
        Macbor: [
            'Eight Mile 125 LC', 'Montana XR1 125 EVO', 'Montana XR5 510', 'Rockster 125 EVO',
            'Rockster 410', 'Rockster Flat 125 EVO', 'Shifter 125 EVO',
        ],
        Malaguti: [
            'Calvacone', 'Drakon', 'Dune', 'Grizzly', 'Madison', 'MISSION', 'Monte Pro', 'MRX', 'RST 125',
            'Warrior', 'XSM', 'XTM 125', 'Inny',
        ],
        Masai: ['A', 'D', 'Drift', 'K', 'L', 'Ultimate', 'Inny'],
        MBK: [
            'altul', 'Booster', 'Cityliner', 'Flame X', 'MachG', 'Nitro', 'Oceo', 'Ovetto', 'Skycruiser',
            'Waap', 'X-Over', 'X-Power',
        ],
        MIKILON: ['Inny'],
        'MIR Racing': ['MiniGP', 'Moto 4', 'Moto 5', 'Pre 3', 'Pre 4', 'Inny'],
        MOMO: ['Morino'],
        Mondial: ['250 Bialbero', 'HPS 125', 'Piega', 'RZ', 'SMX', 'Inny'],
        'Mondo Motors': [
            'Baxter 500', 'Big Box', 'Brightstar', 'Dragon', 'Hiray', 'Matador', 'Proton', 'Quad Tytan',
            'Raider 500', 'Storm', 'Strict', 'Yester', 'Z500',
        ],
        Morbidelli: [
            'C1002V', 'C652V', 'F125', 'M502N', 'N125V', 'SC125', 'T1002V', 'T1002VX', 'T125', 'T125X',
            'T352X', 'T502X', 'T502XR', 'Inny',
        ],
        Moti: ['Buddy'],
        'Moto Guzzi': [
            '1000 SP', '1200', '750 Strada', '850', 'Airone 250 Sport', 'Bellagio', 'Breva', 'California',
            'Centauro Sport', 'Daytona', 'EV Californian', 'Griso', 'Le Mans', 'Lodola Sport',
            'MGS-01 Corsa', 'Monza', 'Nevada', 'Norge', 'NTX 650', 'Sport 1100', 'Stelvio', 'Stone',
            'V100 Mandello', 'V11', 'V7', 'V85', 'V9', 'Inny',
        ],
        'Moto Magnus': [
            'Capro', 'Carave', 'Classico', 'Grande', 'Ibizzo', 'Jolly', 'Rapido', 'Retro', 'Solatio',
            'T-Rex', 'Veniro', 'Verso', 'Inny',
        ],
        'Moto Morini': [
            '3.5 Sport', '500 Strada', 'Camel 500', 'Dart 400', 'Excalibur 350', 'Montana GS4 50', 'Inny',
        ],
        Motobi: [
            'Orlik', 'Puma', 'Rocky', 'Sowa', 'Spider', 'Sprint', 'Wilga', 'Zip Star', 'Łoś', 'Żbik', 'Inny',
        ],
        Motomar: ['Inny'],
        Motorro: ['Cesar', 'City Hopper', 'Desire', 'Polly', 'Tria', 'Inny'],
        Motowell: ['Kid', 'Magnet', 'Retrosa', 'Yoyo', 'Inny'],
        Motron: [
            'BREEZY', 'CUBERTINO', 'IDEO', 'Nomad', 'Revolver', 'Ventura', 'VIZION', 'VOLTZ', 'WHIZZ',
            'Inny',
        ],
        'MP Korado': [
            'Admiral', 'Adventure', 'Cross', 'DeLux', 'E1', 'Klasik', 'Mini', 'Raptor', 'Solana', 'Trek',
            'Via', 'Via 125', 'Via 2T', 'Inny',
        ],
        MRF: ['Inny'],
        MUDRAX: ['MR-01-125', 'MR-01-150', 'MR-02-125', 'MR-03-125', 'MR-04-125'],
        Munch: ['Mammut'],
        'MV AGUSTA': [
            '350 Sport Ipotesi', '750S', 'Brutale', 'Brutale America', 'Brutale S', 'Dragster', 'F3', 'F4',
            'Raptor X', 'RUSH', 'RVS', 'Superveloce', 'Turismo Veloce', 'Inny',
        ],
        MZ: [
            '1000 SF', '1000S', '125SM', 'Baghira', 'BK', 'ES', 'ETS', 'ETZ', 'ETZ 125 Cross', 'Kanuni',
            'Mastiff 660', 'Moskito', 'RT', 'Saxon Fun 301', 'Silverstar 500', 'Skorpion',
            'Skorpion Traveller', 'Supa 5', 'TS', 'Inny',
        ],
        'Nitro Motors': ['Inny'],
        Niu: ['M', 'M+', 'MQI', 'MQI+', 'N', 'NQI', 'NQX 150', 'NQX 300', 'U'],
        Norton: ['Cafe Racer Manx', 'Commando', 'Dominator', 'ES 2', 'Manx', 'P11 Ranger', 'Inny'],
        NSU: ['175', '201', '251', '301', '351', '500', '501', '502', '600', 'Quick', 'Inny'],
        ODES: ['Patchcross', 'RM', 'Inny'],
        'Orange County Choppers (OCC)': ['Inny'],
        Pannonia: ['P10', 'T1', 'T5', 'T8', 'T9', 'Inny'],
        Peda: ['Desire', 'Eagle', 'Maxisport', 'Rally', 'Shark', 'Speedy', 'Via Warrior', 'Inny'],
        Pegasus: ['Inny'],
        Peugeot: [
            '103 RCX', '103 SPX', '103D', '104', 'BB-1C', 'Belville', 'Buxy', 'Citystar', 'Django',
            'e-STREETZONE', 'Elyseo', 'Elystar Advantage', 'Geopolis', 'Jet C-tech', 'Jet Force', 'Kisbee',
            'Looxor', 'Ludix 2', 'Metropolis', 'New Vivacity', 'PM-01', 'Pulsion', 'RX 80', 'Satelis', 'SC',
            'Snake', 'Speedake', 'Speedfight', 'Squab', 'ST', 'Street Zone', 'SV', 'TKR', 'Trekker', 'Tweet',
            'V-Clic', 'Vivacity', 'Vogue', 'WRC 206', 'WRC 307', 'X-Fight Furious', 'XP 50', 'XP 6', 'XP400',
            'XPS Enduro', 'XPS SM', 'XR6', 'Zenith', 'Inny',
        ],
        'Phelon and moore': ['Capetown 7S', 'Capetown 7X', 'Panthette X'],
        Piaggio: [
            'Albatros', 'Ape 50 Pickup', 'Ape 50 Van', 'Ape Calessino', 'Ape Classic Pickup',
            'Ape Classic Van', 'Beverly', 'Bravo', 'Carnaby', 'Ciao', 'Cosa', 'Diesis', 'Energy', 'ET',
            'FLY', 'Free', 'Gran Sport', 'Grillo', 'GS', 'Hexagon', 'Liberty', 'Medley', 'MP-3', 'NRG',
            'NTT', 'P', 'PK', 'PX', 'Quartz', 'Sfera', 'SI', 'Skipper', 'SKR', 'Storm', 'Super Bravo', 'T',
            'TPH', 'Trackmaster', 'Typhoon', 'Vespa', 'X10', 'X7', 'X8', 'X9', 'Xevo', 'ZIP', 'Inny',
        ],
        'Pit Bike IMR': ['Corse', 'GP20', 'Inny'],
        Pitgang: ['110XD Enduro', '125XD Enduro', '140XD', '140XD Enduro', '300XD Enduro'],
        Polaris: [
            'Beast', 'Hawkeye', 'Outlaw', 'Phoenix', 'Predator', 'Ranger', 'Ranger 6x6', 'Ranger EV',
            'Ranger XP', 'RZR', 'Sawtooth Base', 'Scrambler', 'Sportsman', 'Trail Boss', 'X2', 'Inny',
        ],
        Polovolt: ['Extreme', 'M-20', 'M20 Pro', 'RS-12', 'ST-16'],
        Powerland: ['Taigen', 'Taigen S'],
        Puch: [
            'Alabama', 'Cobra', 'Condor', 'Korrado', 'Magnum', 'Maxi', 'Minicross', 'Monza', 'MS', 'MV',
            'NRG', 'S4', 'Sabre', 'TL', 'VS', 'Winners', 'Inny',
        ],
        QJMOTOR: [
            '900 S', '900 SX', 'COV 125X', 'FORT 125', 'FORT 350', 'FORTRESS 350', 'MTX 125', 'SFA 1000',
            'SFA 300', 'SFA 600', 'SRK 125R', 'SRK 125S', 'SRK 700', 'SRK 800', 'SRK 800RR', 'SRK 921',
            'SRK 921RR', 'SRT 125DX', 'SRT 300DX', 'SRT 450RX', 'SRT 550 SX', 'SRT 550X', 'SRT 600SX',
            'SRT 800S', 'SRT 800SX', 'SRT900S', 'SRT900SX', 'SRV 12', 'SRV 125', 'SRV 125V', 'SRV 600V',
            'SRV 700', 'SVT 650', 'SVT 650X', 'TRX 125', 'Inny',
        ],
        Quadro: [
            '3', '3 Edelweiss', '350 D', '4', '4 Adventure', '4 Steinbock', '4D', 'AATW R', 'Oxygen',
            'Oxygen 3', 'Oxygen 3 Evo', 'Qooder', 'QV3', 'S',
        ],
        RASSLER: ['Inny'],
        Redline: ['Revolt', 'Revolution', 'Inny'],
        Rerode: ['R1', 'R1+', 'R1+S'],
        Rewaco: ['HS', 'PUR3', 'RF1', 'RF1 GT', 'RF2'],
        REX: ['SMC', 'Inny'],
        Rieju: [
            'Aventura 125', 'Aventura 500', 'Marathon', 'Marathon Pro', 'MR Pro 300i', 'MR Racing 300i',
            'MRT', 'MRT Pro', 'MRT Pro SM', 'MRT SM', 'MRX', 'MRX Pro', 'MX', 'MX Disk', 'NKD', 'Pacific',
            'RRX', 'RRX Spike', 'RS2', 'RS2 FR', 'RS2 Pro', 'SMX', 'SMX FR', 'SMX Pro', 'SMX Street',
            'Tango', 'Tango Motard', 'Tango Pro', 'Tangoo!', 'Inny',
        ],
        RM: ['800 Duo', 'Inny'],
        Romet: [
            '727', '777', 'AMAX', 'Ariic', 'ARROW FLY', 'ATV', 'C1', 'CAFFE', 'CHART', 'City 50', 'CRS',
            'Division', 'EV1', 'FR 750', 'Gobi', 'GT MAX', 'Hammer', 'JET', 'K', 'Kadet', 'NS', 'OGAR',
            'Ogar 202', 'Ogar 900', 'PONY', 'PONY MINI', 'R', 'RCR', 'Retro', 'RXC', 'RXL', 'RXL50', 'SCMB',
            'SOFT', 'Soft Chopper', 'TANK', 'Target', 'Touch', 'TREVIS', 'Vanillia', 'VXL', 'XDV', 'Z',
            'Zenit', 'Zetka', 'ZXT', 'Inny',
        ],
        'Royal Enfield': [
            'Bear 650', 'Bullet', 'Bullet 350', 'Classic', 'Continental', 'Guerrilla', 'Himalayan', 'HNTR',
            'Interceptor', 'Meteor', 'Scram', 'Shotgun', 'Super Meteor', 'Inny',
        ],
        Sachs: [
            'B', 'Balboa', 'Formula 1', 'Jupiter', 'Jupiter Safir', 'Lotus', 'Madass', 'Panter', 'Roadster',
            'Ultra RS', 'V5 Racing', 'X-Road', 'XTC Racing', 'ZX', 'ZZ', 'Inny',
        ],
        SARINI: ['AMO', 'ARNO', 'FIBI', 'PRITI', 'Sole', 'TITO', 'VELO', 'Inny'],
        Scootworks: ['Challenge'],
        Seat: ['MÓ'],
        Segway: ['AT5', 'Fugleman UT10', 'Snarler AT10', 'Snarler AT6', 'Villain SX1', 'Inny'],
        Sherco: ['2T Trials', '4T', 'Enduro', 'Kid', 'SM', 'Trial', 'Inny'],
        SHERP: ['PICKUP', 'PRO'],
        Shineray: ['Extreme', 'Lanca', 'Roadwin', 'XY', 'Inny'],
        SHL: ['Inny'],
        Simson: ['Easy 01', 'KR', 'Inny'],
        Skyjet: ['Inny'],
        SMC: ['Buzz', 'Florett', 'Jumbo', 'Online', 'RAM', 'Razeer', 'Snake', 'Inny'],
        'Sokół': ['1000 M111', '125', '200 M411', '500 M311', '600 M211', 'Inny'],
        'Stark Future': ['EX', 'MX', 'VARG', 'Inny'],
        Stels: ['Inny'],
        Summit: ['HY', 'ZF', 'Inny'],
        Sunbeam: ['Model 7', 'Model 8', 'Inny'],
        'Super Soco': ['CPx', 'CUX', 'E-MAX', 'TC', 'TC MAX', 'TS', 'TSX', 'Inny'],
        Surron: ['Light Bee', 'Light Bee S', 'Storm Bee', 'Ultra-Bee', 'Inny'],
        Suzuki: [
            'Address', 'AP', 'Avenis', 'Bandit', 'Boulevard', 'Burgman', 'DL', 'DR', 'DR-Z', 'EN', 'ER',
            'Gladius', 'GN', 'GR', 'GS', 'GSR', 'GSX', 'GSX 1000', 'GSX-F - Katana', 'GSX-R', 'GV', 'GW 250',
            'GX', 'GZ', 'Hayabusa', 'Intruder', 'Katana', 'Kingquad', 'Marauder', 'OR', 'Papia FD', 'PV',
            'Raider', 'RAN', 'RF', 'RG', 'RGV', 'RL', 'RM', 'RM-Z', 'RMX', 'RV', 'S', 'S1', 'Satria',
            'Savage', 'Sepia', 'Shogun', 'SMX', 'SP', 'Sprinter', 'SV', 'T', 'TC', 'TL', 'TM', 'TR', 'TU',
            'TXR', 'V-STROM', 'VL 1500 Intruder LC - Boulevard C90', 'VL 800 Volusia',
            'VL 800 Volusia - Boulevard C50', 'VS', 'VX', 'VZ', 'XF', 'Inny',
        ],
        SWM: [
            'Ace of spades', 'Binsen', 'Gran Turismo`', 'RS 125 R', 'RS 300 R', 'RS 500 R', 'Silver Vase',
            'Six Days', 'SM 125 R', 'SM 450 R', 'SM 500 R', 'Super Dual T', 'Superdual X', 'Inny',
        ],
        SYM: [
            'ADX', 'Citycom', 'CRUiSYM', 'DD', 'Fiddle', 'GTS', 'HD', 'Jet', 'Jet X', 'Joymax', 'Joyride',
            'MAXSYM', 'MIO', 'Orbit', 'Symphony', 'Symply', 'VS', 'XS', 'X’PRO', 'Inny',
        ],
        Talaria: ['Komodo', 'Sting L1e', 'Sting MX', 'Sting R', 'XXX', 'Inny'],
        'TAO MOTORS': ['Inny'],
        TGB: [
            'Akros', 'ATV425', 'Bellavita', 'BK1', 'Blade', 'Express', 'F', 'F409', 'GFS', 'Hawk', 'Laser',
            'Mystique', 'Octane', 'Orion', 'R50X Bullet', 'Sienna', 'Tryton', 'Urban', 'Vivo', 'Voodoo',
            'Inny',
        ],
        Thumpstar: [
            'TSB 110', 'TSB 125E', 'TSB 140', 'TSB 70', 'TSC 110', 'TSC 125', 'TSC 140', 'TSR 140',
            'TSX 212',
        ],
        TM: ['Cross', 'Enduro', 'SMM', 'SMR', 'SMX', 'Inny'],
        Torq: ['Moko'],
        Torrot: ['Muvi', 'MX1', 'MX2', 'MX3', 'SM1', 'SM2', 'TR1', 'TR2'],
        Triango: ['125', '50'],
        Triton: ['T', 'Inny'],
        Triumph: [
            'Adventurer', 'America', 'Bonneville', 'Bonneville Bobber', 'Daytona', 'Legend TT', 'Rocket',
            'Scrambler', 'Speed Four', 'Speed Triple', 'Speed Twin', 'Speedmaster', 'Sprint',
            'Street Scrambler', 'Street Triple', 'Street Twin', 'T', 'T25T', 'Thruxton', 'Thunderbird',
            'Tiger', 'Tiger Cub', 'TR6R', 'Trident', 'Trophy', 'TT', 'Inny',
        ],
        Tromox: ['MC10', 'Mino B', 'Pesgo one', 'Ukko S', 'Inny'],
        TUATARA: ['Inny'],
        UM: ['Renegade Commando', 'Renegade Freedom', 'Renegade Sport', 'Renegade Vegas', 'Inny'],
        UPMoto: [
            'T-Crosser 525', 'T-Crosser 625', 'T-Crosser X 1000', 'T-Crosser X 1000 MUD Pro',
            'T-Crosser X 1000 Wide', 'T-Crosser X 650', 'T-Crosser X 800', 'U-Crosser 1000-3 HVAC',
            'U-Crosser 1000-6 HVAC', 'U-Crosser 650-3', 'U-Crosser 800-3',
        ],
        Ural: [
            'Custom', 'IMZ', 'K-750', 'M-61', 'M-62', 'M-63', 'M-66', 'M-67', 'M-72', 'Patrol', 'Retro',
            'Tourist', 'Wolf', 'Inny',
        ],
        Vectrix: ['VX-1', 'VX-2'],
        VELEX: ['Comfort', 'Egreen', 'M1', 'M2', 'M8', 'TRIP'],
        Velocifero: ['City-One', 'City-X', 'Mobster', 'Tennis'],
        Ventus: ['Inny'],
        Vespa: [
            'Elettrica', 'ET', 'Grantourismo', 'GS', 'GT', 'GTS', 'GTV-LXV', 'LX', 'Montec', 'P', 'PK',
            'Primavera', 'PX', 'Special', 'Sprint', 'Super', 'V', 'VBB', 'Vespino', 'VNB', 'Inny',
        ],
        Victory: ['Hammer', 'Kingpin', 'V', 'Vegas', 'Vision', 'Inny'],
        Vincent: ['Black Lightning', 'Black Shadow', 'Comet', 'Meteor', 'Rapide'],
        Vmoto: [
            'CITI', 'CPX', 'CPX EXLPORER', 'CPX PRO', 'CPX-D', 'CPX-D EXPLORER', 'CUX PRO', 'OFF-R', 'ON-R',
            'STASH', 'TC', 'TC MAX', 'TC WANDERER PRO', 'TS STREET HUNTER PRO', 'TSX', 'VS1', 'VS2 CITI',
            'VS3',
        ],
        VOGE: [
            '300AC', '300ACX', '300DS', '300GY RALLY', '300R', '500AC', '500DS', '500DSX', '500R', '525ACX',
            '525DSX', '625DSX', '650DSX', '800 Rally', '900DSX', 'ER10', 'R125', 'R125S', 'RR660S', 'SR1',
            'SR1 ADV', 'SR4 MAX', 'SR450X', 'Inny',
        ],
        WFM: ['M', 'Osa', 'SHL', 'Inny'],
        WK: ['Inny'],
        WSK: ['M06', 'M21', 'Inny'],
        'X-Moto': ['ostatní', 'Inny'],
        XMOTOS: ['XB39', 'XB88', 'Inny'],
        XTR: [
            '701 E-start', '701 Pull Start', '702 E-start', '702 Pull Start', 'A', 'E-702 800W', 'E-M14 PRO',
            'Farmer 150', 'Farmer 150 Pro', 'Inny',
        ],
        Yadea: ['C-line'],
        Yamaha: [
            'Aerox', 'AG', 'Air Tricker', 'Airport', 'AT', 'ATI', 'Autolube', 'Axis', 'Banshee', 'Beluga',
            'Big Bear', 'Boulevard', 'BT', 'Bulldog', 'BW', 'BWS', 'CA', 'CR', 'Crypton', 'CS', 'CT', 'CT1',
            'Cute', 'Cygnus', 'D\'elight', 'Drag Star', 'DS', 'DT', 'EW', 'F1', 'FJ', 'FJR', 'FS1', 'FZ',
            'FZ6', 'FZ8', 'FZR', 'FZS', 'FZX', 'Grizzly', 'GT', 'GTS', 'HS', 'IT', 'JOG', 'JT', 'Kodiak',
            'L5', 'Lagenda', 'LB', 'LC', 'Libero', 'Majesty', 'Maxim', 'Maxster', 'MBK', 'Midnight Star',
            'Mio', 'MT', 'MX', 'Neos', 'NIKEN', 'NMAX', 'NXC', 'Passol', 'PW', 'R1', 'R125', 'R3', 'R6',
            'R7', 'R9', 'Radian', 'Raider', 'Raptor', 'Razz', 'RD', 'Riva', 'Road Star', 'Royal Star', 'RS',
            'RSX', 'RT', 'RX', 'RXS', 'RXZ', 'RZ', 'SA', 'Salient', 'Scorpio', 'SCR', 'SDR', 'SG',
            'Skyliner', 'Slider', 'SR', 'SRX', 'SS TWO', 'Super Tenere', 'SX', 'SZR', 'TA', 'Target', 'TDM',
            'TDR', 'Tenere', 'Thunderace', 'Thundercat', 'Tiara', 'Tmax', 'Touch', 'Tracer', 'Tricity',
            'TRX', 'TT', 'TTR', 'TW', 'TX', 'TY', 'TZ', 'TZM', 'TZR', 'V', 'V Star', 'V-MAX', 'Vega',
            'Venture', 'Vino', 'Virago', 'VRR', 'Warrior', 'Wild star', 'Wolverine', 'WR', 'X', 'X-max',
            'XC', 'XJ', 'XJR', 'XS', 'XSR', 'XT', 'XTX', 'XTZ', 'XV', 'XVS', 'XVZ', 'XZ', 'Yamahopper QT',
            'YB', 'YBR', 'YDS', 'YFM', 'YFZ', 'YGS', 'YR', 'YS', 'YSR', 'YX', 'YZ', 'YZF', 'YZR', 'Z',
            'Zest', 'Zico', 'Zipp', 'ZR', 'Zuma', 'Inny',
        ],
        Yamasaki: ['125', 'Inny'],
        Yuki: ['Inny'],
        YZM: ['M19', 'T19'],
        Zast: ['Inny'],
        Zefir: ['1'],
        Zero: ['DS', 'DSR', 'FX', 'S', 'SR'],
        Zipp: [
            'Appia', 'Astec', 'Azer', 'GP500', 'JZW-50', 'LaVISSA 125', 'Manic', 'Manic 125', 'Otis',
            'Otis plus', 'PARCO', 'PRO RS 125', 'PRO RS50', 'Quantum', 'Raven', 'Raven 125', 'Raven LUX 125',
            'Roadstar', 'Rooster', 'Salmo', 'Simpli', 'STEED', 'TOPS', 'Vapor', 'Vega', 'Volteno', 'VZ-1',
            'VZ-2', 'VZ-3', 'VZ-50', 'ZIPP 125', 'Inny',
        ],
        Zonda: ['110', '150', '200', '250', '300'],
        Zongshen: ['ZS', 'Inny'],
        Zontes: [
            '125 C2', '125 G1 Aluminium', '125 G1 Spoke', '125 GK', '125 Z2', '125C', '125D', '125E', '125M',
            '125U', '125U1', '125X', '310M', '310R', '310T', '310V', '310X', '312V', '350D', '350E', '350GK',
            '350R', '350T', '350V', '350VX', '350X', '368E', '368G', '368G V2', '703 RR', '703F', '703RR',
            '703T', 'M310', 'Inny',
        ],
        Zumico: [
            'Aion', 'Avatar', 'Dynamic', 'Eos', 'GR1100', 'Ignis', 'Mac', 'ORS 150', 'ORS 250', 'Quad',
            'Quick', 'Ronin', 'Shiva', 'Inny',
        ],
        Zundapp: ['CS', 'Famel XF', 'KS', 'M25', 'Z3', 'ZR', 'Inny'],
        Zuumav: ['A1', 'H7', 'K3', 'K7', 'K8', 'S2', 'S6'],
        'ZX MOTO': ['250MX', '500RR', '820RR'],
    },
};
