server:
  port: 8085

spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://${CHAT_DB_HOST:localhost}:${CHAT_DB_PORT:5436}/${CHAT_DB_NAME:chat_db}
    username: ${CHAT_DB_USER:postgres}
    password: ${CHAT_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvckNhck1hcmtldEp3dFRva2VuMjAyNA==}
  access-token-expiry-ms: 900000      # 15 minutes
  refresh-token-expiry-ms: 604800000  # 7 days

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USER:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info